// ─── ENGLISH KIDS — COMPLETE CURRICULUM DATA v4 ──────────────────
// 4 levels · ~600+ words, phrases & dialogues · Age 3–10

const LEVELS = [
  { id: 'starter',      label: 'Starter',     age: '3–4',  stars: 1, color: '#ff6b9d', icon: '🌱' },
  { id: 'basic',        label: 'Básico',      age: '4–6',  stars: 2, color: '#ffd93d', icon: '🌿' },
  { id: 'intermediate', label: 'Intermedio',  age: '6–8',  stars: 3, color: '#4d96ff', icon: '🌳' },
  { id: 'advanced',     label: 'Avanzado',    age: '8–10', stars: 4, color: '#c77dff', icon: '🏆' },
];

const CATEGORIES = {
  // ══════════════════════════════════════════════════════════════
  // STARTER  3–4 años
  // ══════════════════════════════════════════════════════════════
  starter: [
    { id: 'animals_s', label: 'Animales', icon: '🐾', color: '#ff6b6b',
      items: [
        {en:'Cat',     es:'Gato',      e:'1f431', ex:'I love cats!'},
        {en:'Dog',     es:'Perro',     e:'1f436', ex:'My dog is friendly.'},
        {en:'Bird',    es:'Pájaro',    e:'1f426', ex:'The bird can fly.'},
        {en:'Fish',    es:'Pez',       e:'1f41f', ex:'I have a fish at home.'},
        {en:'Rabbit',  es:'Conejo',    e:'1f430', ex:'The rabbit is fluffy.'},
        {en:'Bear',    es:'Oso',       e:'1f43b', ex:'The bear is big and strong.'},
        {en:'Lion',    es:'León',      e:'1f981', ex:'The lion is the king!'},
        {en:'Duck',    es:'Pato',      e:'1f986', ex:'The duck swims in the pond.'},
        {en:'Frog',    es:'Rana',      e:'1f438', ex:'The frog is green.'},
        {en:'Cow',     es:'Vaca',      e:'1f404', ex:'The cow says moo!'},
        {en:'Horse',   es:'Caballo',   e:'1f434', ex:'I can ride a horse!'},
        {en:'Pig',     es:'Cerdo',     e:'1f437', ex:'The pig is pink.'},
        {en:'Sheep',   es:'Oveja',     e:'1f411', ex:'The sheep says baa!'},
        {en:'Chicken', es:'Pollo',     e:'1f414', ex:'The chicken lays eggs.'},
        {en:'Elephant',es:'Elefante',  e:'1f418', ex:'The elephant has a long trunk.'},
        {en:'Monkey',  es:'Mono',      e:'1f412', ex:'The monkey loves bananas.'},
        {en:'Tiger',   es:'Tigre',     e:'1f42f', ex:'The tiger has orange stripes.'},
        {en:'Penguin', es:'Pingüino',  e:'1f427', ex:'Penguins cannot fly.'},
      ]},
    { id: 'colors_s', label: 'Colores', icon: '🌈', color: '#fbbf24',
      items: [
        {en:'Red',    es:'Rojo',     e:'2764',   ex:'My favourite colour is red.'},
        {en:'Blue',   es:'Azul',     e:'1f499',  ex:'The sky is blue.'},
        {en:'Yellow', es:'Amarillo', e:'1f49b',  ex:'The sun is yellow.'},
        {en:'Green',  es:'Verde',    e:'1f49a',  ex:'The grass is green.'},
        {en:'Orange', es:'Naranja',  e:'1f9e1',  ex:'I like orange juice.'},
        {en:'Pink',   es:'Rosa',     e:'1f497',  ex:'The flower is pink.'},
        {en:'Purple', es:'Morado',   e:'1f49c',  ex:'I have a purple bag.'},
        {en:'White',  es:'Blanco',   e:'1f90d',  ex:'Snow is white.'},
        {en:'Black',  es:'Negro',    e:'1f5a4',  ex:'The night is black.'},
        {en:'Brown',  es:'Marrón',   e:'1f7eb',  ex:'Chocolate is brown.'},
      ]},
    { id: 'fruits_s', label: 'Frutas', icon: '🍎', color: '#6bcb77',
      items: [
        {en:'Apple',      es:'Manzana',   e:'1f34e', ex:'I eat an apple every day.'},
        {en:'Banana',     es:'Plátano',   e:'1f34c', ex:'Monkeys love bananas!'},
        {en:'Orange',     es:'Naranja',   e:'1f34a', ex:'The orange is sweet.'},
        {en:'Strawberry', es:'Fresa',     e:'1f353', ex:'Strawberries are red and sweet.'},
        {en:'Grapes',     es:'Uvas',      e:'1f347', ex:'I love purple grapes.'},
        {en:'Watermelon', es:'Sandía',    e:'1f349', ex:'Watermelon is great in summer.'},
        {en:'Peach',      es:'Melocotón', e:'1f351', ex:'The peach is soft and sweet.'},
        {en:'Pear',       es:'Pera',      e:'1f350', ex:'A pear is green or yellow.'},
        {en:'Cherry',     es:'Cereza',    e:'1f352', ex:'Cherries are small and red.'},
        {en:'Lemon',      es:'Limón',     e:'1f34b', ex:'Lemons are yellow and sour.'},
        {en:'Mango',      es:'Mango',     e:'1f96d', ex:'The mango is tropical and sweet.'},
        {en:'Pineapple',  es:'Piña',      e:'1f34d', ex:'A pineapple is yellow inside.'},
      ]},
    { id: 'numbers_s', label: 'Números', icon: '🔢', color: '#4d96ff',
      items: [
        {en:'One',   es:'Uno',    e:'0031-20e3', ex:'I have one cat.'},
        {en:'Two',   es:'Dos',    e:'0032-20e3', ex:'I have two eyes.'},
        {en:'Three', es:'Tres',   e:'0033-20e3', ex:'Three little birds!'},
        {en:'Four',  es:'Cuatro', e:'0034-20e3', ex:'I have four pencils.'},
        {en:'Five',  es:'Cinco',  e:'0035-20e3', ex:'Five fingers on my hand.'},
        {en:'Six',   es:'Seis',   e:'0036-20e3', ex:'There are six apples.'},
        {en:'Seven', es:'Siete',  e:'0037-20e3', ex:'Seven days in a week.'},
        {en:'Eight', es:'Ocho',   e:'0038-20e3', ex:'An octopus has eight legs.'},
        {en:'Nine',  es:'Nueve',  e:'0039-20e3', ex:'I can count to nine.'},
        {en:'Ten',   es:'Diez',   e:'1f51f',     ex:'I can count to ten!'},
      ]},
    { id: 'body_s', label: 'Cuerpo', icon: '👁️', color: '#f97316',
      items: [
        {en:'Head',   es:'Cabeza',  e:'1f9e0', ex:'Touch your head!'},
        {en:'Eye',    es:'Ojo',     e:'1f441', ex:'My eyes are brown.'},
        {en:'Nose',   es:'Nariz',   e:'1f443', ex:'My nose is small.'},
        {en:'Mouth',  es:'Boca',    e:'1f444', ex:'I use my mouth to talk.'},
        {en:'Ear',    es:'Oreja',   e:'1f442', ex:'I listen with my ear.'},
        {en:'Hand',   es:'Mano',    e:'1f91a', ex:'I wave with my hand.'},
        {en:'Foot',   es:'Pie',     e:'1f9b6', ex:'I kick with my foot.'},
        {en:'Leg',    es:'Pierna',  e:'1f9b5', ex:'I run with my legs.'},
        {en:'Arm',    es:'Brazo',   e:'1f4aa', ex:'I hug with my arms.'},
        {en:'Hair',   es:'Pelo',    e:'1f9b1', ex:'My hair is long.'},
        {en:'Teeth',  es:'Dientes', e:'1f9b7', ex:'Brush your teeth every day!'},
        {en:'Tongue', es:'Lengua',  e:'1f445', ex:'I taste with my tongue.'},
        {en:'Tummy',  es:'Barriga', e:'1f7e1', ex:'My tummy is full!'},
        {en:'Back',   es:'Espalda', e:'1f9b4', ex:'Keep your back straight.'},
      ]},
    { id: 'shapes_s', label: 'Formas', icon: '🔷', color: '#14b8a6',
      items: [
        {en:'Circle',    es:'Círculo',    e:'2b55',   ex:'The sun is a circle.'},
        {en:'Square',    es:'Cuadrado',   e:'1f7e5',  ex:'A box is a square.'},
        {en:'Triangle',  es:'Triángulo',  e:'1f53a',  ex:'A pizza slice is a triangle.'},
        {en:'Star',      es:'Estrella',   e:'2b50',   ex:'I can see a star!'},
        {en:'Heart',     es:'Corazón',    e:'2764',   ex:'I draw a heart for you.'},
        {en:'Diamond',   es:'Diamante',   e:'1f4a0',  ex:'A diamond sparkles.'},
        {en:'Rectangle', es:'Rectángulo', e:'1f7e6',  ex:'The door is a rectangle.'},
        {en:'Oval',      es:'Óvalo',      e:'1f48a',  ex:'An egg is an oval.'},
      ]},
    { id: 'greetings_s', label: 'Saludos', icon: '👋', color: '#c77dff',
      items: [
        {en:'Hello',         es:'Hola',           e:'1f44b', ex:'Hello! Nice to meet you!'},
        {en:'Goodbye',       es:'Adiós',           e:'1f44d', ex:'Goodbye! See you soon!'},
        {en:'Please',        es:'Por favor',       e:'1f64f', ex:'Can I have one please?'},
        {en:'Thank you',     es:'Gracias',         e:'1f60a', ex:'Thank you very much!'},
        {en:'Yes',           es:'Sí',              e:'2705',  ex:'Yes, I like it!'},
        {en:'No',            es:'No',              e:'274c',  ex:'No, thank you.'},
        {en:'Sorry',         es:'Lo siento',       e:'1f972', ex:'I am sorry, my friend.'},
        {en:'Good morning',  es:'Buenos días',     e:'1f305', ex:'Good morning! How are you?'},
        {en:'Good night',    es:'Buenas noches',   e:'1f319', ex:'Good night! Sleep well!'},
        {en:'Good afternoon',es:'Buenas tardes',   e:'1f31e', ex:'Good afternoon, everyone!'},
      ]},
    { id: 'phrases_starter', label: 'Mis frases', icon: '💬', color: '#ff6b9d',
      items: [
        {en:'My name is...',         es:'Me llamo...',           e:'1f476', p:true},
        {en:'I am three',            es:'Tengo tres años',       e:'0033-20e3', p:true},
        {en:'I am four',             es:'Tengo cuatro años',     e:'0034-20e3', p:true},
        {en:'I like cats',           es:'Me gustan los gatos',   e:'1f431', p:true},
        {en:'I like dogs',           es:'Me gustan los perros',  e:'1f436', p:true},
        {en:'I am happy',            es:'Estoy feliz',           e:'1f601', p:true},
        {en:'I am sad',              es:'Estoy triste',          e:'1f622', p:true},
        {en:'I am hungry',           es:'Tengo hambre',          e:'1f974', p:true},
        {en:'I am tired',            es:'Estoy cansado',         e:'1f971', p:true},
        {en:'I am sleepy',           es:'Tengo sueño',           e:'1f634', p:true},
        {en:'I want milk',           es:'Quiero leche',          e:'1f95b', p:true},
        {en:'I want a biscuit',      es:'Quiero una galleta',    e:'1f36a', p:true},
        {en:'I love you',            es:'Te quiero',             e:'2764', p:true},
        {en:'Look at me!',           es:'¡Mírame!',              e:'1f440', p:true},
        {en:'That is a cat',         es:'Eso es un gato',        e:'1f431', p:true},
        {en:'That is a dog',         es:'Eso es un perro',       e:'1f436', p:true},
        {en:'The cat is big',        es:'El gato es grande',     e:'1f431', p:true},
        {en:'The dog is small',      es:'El perro es pequeño',   e:'1f436', p:true},
        {en:'One two three, go!',    es:'Uno dos tres, ¡ya!',    e:'1f3c3', p:true},
        {en:'Touch your nose',       es:'Toca tu nariz',         e:'1f443', p:true},
        {en:'Touch your head',       es:'Toca tu cabeza',        e:'1f9e0', p:true},
        {en:'Clap your hands',       es:'Da palmitas',           e:'1f44f', p:true},
        {en:'Jump up!',              es:'¡Salta!',               e:'1f939', p:true},
        {en:'Sit down',              es:'Siéntate',              e:'1fa91', p:true},
        {en:'Stand up',              es:'Levántate',             e:'1f9cd', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // BÁSICO  4–6 años
  // ══════════════════════════════════════════════════════════════
  basic: [
    { id: 'food_b', label: 'Comida', icon: '🍕', color: '#f97316',
      items: [
        {en:'Bread',    es:'Pan',         e:'1f35e', ex:'I eat bread for breakfast.'},
        {en:'Milk',     es:'Leche',       e:'1f95b', ex:'Milk is good for your bones.'},
        {en:'Egg',      es:'Huevo',       e:'1f95a', ex:'I like eggs for breakfast.'},
        {en:'Pizza',    es:'Pizza',       e:'1f355', ex:'Pizza is my favourite food!'},
        {en:'Cookie',   es:'Galleta',     e:'1f36a', ex:'Can I have a cookie please?'},
        {en:'Cake',     es:'Tarta',       e:'1f370', ex:'I love birthday cake!'},
        {en:'Ice cream',es:'Helado',      e:'1f368', ex:'Ice cream is cold and sweet.'},
        {en:'Soup',     es:'Sopa',        e:'1f35c', ex:'Hot soup is great in winter.'},
        {en:'Cheese',   es:'Queso',       e:'1f9c0', ex:'I put cheese on my pizza.'},
        {en:'Sandwich', es:'Bocadillo',   e:'1f96a', ex:'I eat a sandwich for lunch.'},
        {en:'Rice',     es:'Arroz',       e:'1f35a', ex:'Rice is eaten in many countries.'},
        {en:'Pasta',    es:'Pasta',       e:'1f35d', ex:'Pasta is my favourite dinner.'},
        {en:'Salad',    es:'Ensalada',    e:'1f957', ex:'Salad is healthy and green.'},
        {en:'Juice',    es:'Zumo',        e:'1f9c3', ex:'I drink orange juice every morning.'},
        {en:'Water',    es:'Agua',        e:'1f4a7', ex:'Drink water every day!'},
        {en:'Chocolate',es:'Chocolate',   e:'1f36b', ex:'I love chocolate.'},
        {en:'Butter',   es:'Mantequilla', e:'1f9c8', ex:'I put butter on my bread.'},
        {en:'Yogurt',   es:'Yogur',       e:'1f964', ex:'Yogurt is creamy and delicious.'},
        {en:'Pancake',  es:'Tortita',     e:'1f95e', ex:'I love pancakes with honey!'},
        {en:'Carrot',   es:'Zanahoria',   e:'1f955', ex:'Carrots are orange and crunchy.'},
      ]},
    { id: 'clothes_b', label: 'Ropa', icon: '👕', color: '#ec4899',
      items: [
        {en:'Shirt',    es:'Camiseta',    e:'1f455', ex:'I wear a blue shirt.'},
        {en:'Pants',    es:'Pantalón',    e:'1f456', ex:'My pants are comfortable.'},
        {en:'Shoes',    es:'Zapatos',     e:'1f45f', ex:'My shoes are new.'},
        {en:'Socks',    es:'Calcetines',  e:'1f9e6', ex:'I have colourful socks.'},
        {en:'Hat',      es:'Sombrero',    e:'1f9e2', ex:'I wear a hat in the sun.'},
        {en:'Dress',    es:'Vestido',     e:'1f457', ex:'She is wearing a pretty dress.'},
        {en:'Jacket',   es:'Chaqueta',    e:'1f9e5', ex:'I wear my jacket when it is cold.'},
        {en:'Scarf',    es:'Bufanda',     e:'1f9e3', ex:'My scarf keeps me warm.'},
        {en:'Gloves',   es:'Guantes',     e:'1f9e4', ex:'I wear gloves in winter.'},
        {en:'Boots',    es:'Botas',       e:'1f97e', ex:'My boots keep my feet dry.'},
        {en:'Coat',     es:'Abrigo',      e:'1f9e5', ex:'My coat is very warm.'},
        {en:'Skirt',    es:'Falda',       e:'1f457', ex:'She has a pink skirt.'},
        {en:'Pyjamas',  es:'Pijama',      e:'1f634', ex:'I wear my pyjamas to bed.'},
        {en:'Trainers', es:'Deportivas',  e:'1f45f', ex:'My trainers are great for sport.'},
        {en:'Jumper',   es:'Jersey',      e:'1f9e5', ex:'My jumper is soft and cosy.'},
        {en:'T-shirt',  es:'Camiseta',    e:'1f455', ex:'I have a stripy T-shirt.'},
      ]},
    { id: 'home_b', label: 'Casa', icon: '🏠', color: '#14b8a6',
      items: [
        {en:'House',   es:'Casa',       e:'1f3e0', ex:'We live in a white house.'},
        {en:'Door',    es:'Puerta',     e:'1f6aa', ex:'Please close the door.'},
        {en:'Bed',     es:'Cama',       e:'1f6cf', ex:'My bed is very comfortable.'},
        {en:'Chair',   es:'Silla',      e:'1fa91', ex:'Sit on the chair please.'},
        {en:'Table',   es:'Mesa',       e:'1f6cb', ex:'We eat at the table.'},
        {en:'Book',    es:'Libro',      e:'1f4da', ex:'I have lots of books.'},
        {en:'Window',  es:'Ventana',    e:'1fa9f', ex:'Look out of the window!'},
        {en:'Bath',    es:'Baño',       e:'1f6c1', ex:'I have a bath every evening.'},
        {en:'Kitchen', es:'Cocina',     e:'1f373', ex:'Mum cooks in the kitchen.'},
        {en:'Garden',  es:'Jardín',     e:'1f33f', ex:'We play in the garden.'},
        {en:'Lamp',    es:'Lámpara',    e:'1f4a1', ex:'Turn on the lamp please.'},
        {en:'TV',      es:'Televisión', e:'1f4fa', ex:'I watch TV after school.'},
        {en:'Fridge',  es:'Nevera',     e:'1f9ca', ex:'The milk is in the fridge.'},
        {en:'Stairs',  es:'Escaleras',  e:'1f3e0', ex:'Walk up the stairs carefully.'},
        {en:'Sofa',    es:'Sofá',       e:'1f6cb', ex:'I sit on the sofa to read.'},
        {en:'Bedroom', es:'Dormitorio', e:'1f6cf', ex:'My bedroom is my favourite room.'},
      ]},
    { id: 'family_b', label: 'Familia', icon: '👨‍👩‍👧', color: '#8b5cf6',
      items: [
        {en:'Mum',         es:'Mamá',      e:'1f469', ex:'My mum is very kind.'},
        {en:'Dad',         es:'Papá',      e:'1f468', ex:'My dad is funny.'},
        {en:'Baby',        es:'Bebé',      e:'1f476', ex:'The baby is sleeping.'},
        {en:'Sister',      es:'Hermana',   e:'1f467', ex:'My sister is my best friend.'},
        {en:'Brother',     es:'Hermano',   e:'1f466', ex:'My brother plays football.'},
        {en:'Grandma',     es:'Abuela',    e:'1f475', ex:'My grandma makes great cookies.'},
        {en:'Grandpa',     es:'Abuelo',    e:'1f474', ex:'My grandpa tells funny stories.'},
        {en:'Aunt',        es:'Tía',       e:'1f469', ex:'My aunt lives far away.'},
        {en:'Uncle',       es:'Tío',       e:'1f468', ex:'My uncle is very tall.'},
        {en:'Friend',      es:'Amigo',     e:'1f91d', ex:'She is my best friend.'},
        {en:'Boy',         es:'Niño',      e:'1f466', ex:'The boy is playing.'},
        {en:'Girl',        es:'Niña',      e:'1f467', ex:'The girl is reading.'},
        {en:'Baby brother',es:'Hermanito', e:'1f476', ex:'My baby brother is cute.'},
        {en:'Baby sister', es:'Hermanita', e:'1f476', ex:'My baby sister loves to laugh.'},
      ]},
    { id: 'days_b', label: 'Días', icon: '📅', color: '#6bcb77',
      items: [
        {en:'Monday',   es:'Lunes',          e:'1f4c5', ex:'On Monday I go to school.'},
        {en:'Tuesday',  es:'Martes',          e:'1f4c5', ex:'On Tuesday we have PE.'},
        {en:'Wednesday',es:'Miércoles',       e:'1f4c5', ex:'Wednesday is my favourite day.'},
        {en:'Thursday', es:'Jueves',          e:'1f4c5', ex:'On Thursday I have music.'},
        {en:'Friday',   es:'Viernes',         e:'1f4c5', ex:'Friday is the last school day.'},
        {en:'Saturday', es:'Sábado',          e:'1f389', ex:'On Saturday I play football.'},
        {en:'Sunday',   es:'Domingo',         e:'26ea',  ex:'On Sunday we visit grandma.'},
        {en:'Today',    es:'Hoy',             e:'1f4c6', ex:'Today is a great day!'},
        {en:'Tomorrow', es:'Mañana',          e:'1f305', ex:'Tomorrow we go to the park.'},
        {en:'Yesterday',es:'Ayer',            e:'1f303', ex:'Yesterday was my birthday.'},
        {en:'Weekend',  es:'Fin de semana',   e:'1f389', ex:'I love the weekend.'},
        {en:'Holiday',  es:'Vacaciones',      e:'1f334', ex:'We go on holiday in summer.'},
      ]},
    { id: 'toys_b', label: 'Juguetes', icon: '🧸', color: '#ff6b9d',
      items: [
        {en:'Ball',      es:'Pelota',  e:'26bd',  ex:'I kick the ball.'},
        {en:'Toy',       es:'Juguete', e:'1f9f8', ex:'My favourite toy is a car.'},
        {en:'Doll',      es:'Muñeca',  e:'1f9b8', ex:'She plays with her doll.'},
        {en:'Car',       es:'Coche',   e:'1f697', ex:'I have a red toy car.'},
        {en:'Bike',      es:'Bici',    e:'1f6b2', ex:'I ride my bike in the park.'},
        {en:'Kite',      es:'Cometa',  e:'1fa81', ex:'I fly my kite in the wind.'},
        {en:'Robot',     es:'Robot',   e:'1f916', ex:'My robot can dance!'},
        {en:'Puzzle',    es:'Puzzle',  e:'1f9e9', ex:'I love doing puzzles.'},
        {en:'Train',     es:'Tren',    e:'1f682', ex:'My toy train goes around the track.'},
        {en:'Balloon',   es:'Globo',   e:'1f388', ex:'I have a red balloon.'},
        {en:'Teddy bear',es:'Osito',   e:'1f9f8', ex:'I sleep with my teddy bear.'},
        {en:'Blocks',    es:'Bloques', e:'1f9f1', ex:'I build towers with blocks.'},
        {en:'Slide',     es:'Tobogán', e:'1f6d9', ex:'I go down the slide fast!'},
        {en:'Swing',     es:'Columpio',e:'1f333', ex:'I love swinging high!'},
      ]},
    { id: 'phrases_basic', label: 'Mis frases', icon: '💬', color: '#f97316',
      items: [
        {en:'My name is Pepe',           es:'Me llamo Pepe',             e:'1f476', p:true},
        {en:'I am five years old',       es:'Tengo cinco años',          e:'0035-20e3', p:true},
        {en:'I am six years old',        es:'Tengo seis años',           e:'0036-20e3', p:true},
        {en:'I live in Spain',           es:'Vivo en España',            e:'1f1ea-1f1f8', p:true},
        {en:'I have a dog',              es:'Tengo un perro',            e:'1f436', p:true},
        {en:'I have a cat',              es:'Tengo un gato',             e:'1f431', p:true},
        {en:'I have a brother',          es:'Tengo un hermano',          e:'1f466', p:true},
        {en:'I have a sister',           es:'Tengo una hermana',         e:'1f467', p:true},
        {en:'My favourite colour is red',es:'Mi color favorito es el rojo',e:'2764', p:true},
        {en:'My favourite food is pizza',es:'Mi comida favorita es la pizza',e:'1f355', p:true},
        {en:'My mum is nice',            es:'Mi mamá es simpática',      e:'1f469', p:true},
        {en:'My dad is funny',           es:'Mi papá es gracioso',       e:'1f468', p:true},
        {en:'I like playing',            es:'Me gusta jugar',            e:'1f3ae', p:true},
        {en:'I like swimming',           es:'Me gusta nadar',            e:'1f3ca', p:true},
        {en:'I like drawing',            es:'Me gusta dibujar',          e:'1f58c', p:true},
        {en:'I do not like vegetables',  es:'No me gustan las verduras', e:'1f966', p:true},
        {en:'Can I have some water?',    es:'¿Me das agua?',             e:'1f4a7', p:true},
        {en:'Can I go to the toilet?',   es:'¿Puedo ir al baño?',        e:'1f6bd', p:true},
        {en:'I can jump',                es:'Puedo saltar',              e:'1f939', p:true},
        {en:'I can run fast',            es:'Puedo correr rápido',       e:'1f3c3', p:true},
        {en:'I cannot swim',             es:'No puedo nadar',            e:'1f6ab', p:true},
        {en:'It is sunny today',         es:'Hoy hace sol',              e:'2600', p:true},
        {en:'It is raining today',       es:'Hoy llueve',                e:'1f327', p:true},
        {en:'Today is Monday',           es:'Hoy es lunes',              e:'1f4c5', p:true},
        {en:'I am going to school',      es:'Voy al colegio',            e:'1f3eb', p:true},
        {en:'School is fun!',            es:'¡El colegio mola!',         e:'1f3eb', p:true},
        {en:'I am wearing a red shirt',  es:'Llevo una camiseta roja',   e:'1f455', p:true},
        {en:'This is my friend',         es:'Este es mi amigo',          e:'1f91d', p:true},
        {en:'Come and play with me!',    es:'¡Ven a jugar conmigo!',     e:'1f3ae', p:true},
        {en:'That is not mine',          es:'Eso no es mío',             e:'274c', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // INTERMEDIO  6–8 años
  // ══════════════════════════════════════════════════════════════
  intermediate: [
    { id: 'actions_i', label: 'Verbos', icon: '🏃', color: '#ff6b6b',
      items: [
        {en:'Run',    es:'Correr',    e:'1f3c3', ex:'I can run very fast!'},
        {en:'Jump',   es:'Saltar',    e:'1f939', ex:'How high can you jump?'},
        {en:'Walk',   es:'Caminar',   e:'1f6b6', ex:'I walk to school every day.'},
        {en:'Swim',   es:'Nadar',     e:'1f3ca', ex:'I swim in the pool.'},
        {en:'Dance',  es:'Bailar',    e:'1f483', ex:'I love to dance to music.'},
        {en:'Sing',   es:'Cantar',    e:'1f3a4', ex:'I sing in the school choir.'},
        {en:'Read',   es:'Leer',      e:'1f4da', ex:'I read every night before bed.'},
        {en:'Write',  es:'Escribir',  e:'270d',  ex:'I write in my notebook.'},
        {en:'Draw',   es:'Dibujar',   e:'1f58c', ex:'I draw animals and flowers.'},
        {en:'Eat',    es:'Comer',     e:'1f372', ex:'I eat three meals a day.'},
        {en:'Drink',  es:'Beber',     e:'1f964', ex:'I drink water after sport.'},
        {en:'Sleep',  es:'Dormir',    e:'1f634', ex:'I sleep for eight hours.'},
        {en:'Play',   es:'Jugar',     e:'1f3ae', ex:'I play with my friends at break.'},
        {en:'Fly',    es:'Volar',     e:'1f6eb', ex:'Birds and planes can fly.'},
        {en:'Climb',  es:'Trepar',    e:'1f9d7', ex:'I climb the tree in the garden.'},
        {en:'Ride',   es:'Montar',    e:'1f6b4', ex:'I can ride a bike.'},
        {en:'Cook',   es:'Cocinar',   e:'1f373', ex:'My mum loves to cook.'},
        {en:'Paint',  es:'Pintar',    e:'1f58c', ex:'I paint pictures at school.'},
        {en:'Laugh',  es:'Reír',      e:'1f602', ex:'He makes me laugh every day.'},
        {en:'Cry',    es:'Llorar',    e:'1f622', ex:'The baby cries when hungry.'},
        {en:'Shout',  es:'Gritar',    e:'1f4e3', ex:'Do not shout in the library!'},
        {en:'Whisper',es:'Susurrar',  e:'1f910', ex:'She whispered a secret to me.'},
        {en:'Help',   es:'Ayudar',    e:'1f91d', ex:'Can you help me please?'},
        {en:'Share',  es:'Compartir', e:'1f91c', ex:'Please share your toys.'},
      ]},
    { id: 'adjectives_i', label: 'Adjetivos', icon: '✨', color: '#fbbf24',
      items: [
        {en:'Big',      es:'Grande',    e:'1f4a5', ex:'The elephant is very big.'},
        {en:'Small',    es:'Pequeño',   e:'1f424', ex:'The mouse is very small.'},
        {en:'Fast',     es:'Rápido',    e:'1f4a8', ex:'The cheetah is very fast.'},
        {en:'Slow',     es:'Lento',     e:'1f422', ex:'The tortoise is very slow.'},
        {en:'Happy',    es:'Feliz',     e:'1f601', ex:'I feel happy today!'},
        {en:'Sad',      es:'Triste',    e:'1f622', ex:'She is sad because she lost her toy.'},
        {en:'Funny',    es:'Gracioso',  e:'1f602', ex:'The clown is very funny.'},
        {en:'Angry',    es:'Enfadado',  e:'1f621', ex:'He gets angry sometimes.'},
        {en:'Tired',    es:'Cansado',   e:'1f971', ex:'I am tired after school.'},
        {en:'Hungry',   es:'Hambriento',e:'1f974', ex:'I am hungry, it is lunchtime!'},
        {en:'Hot',      es:'Caliente',  e:'1f975', ex:'The soup is very hot.'},
        {en:'Cold',     es:'Frío',      e:'1f976', ex:'It is cold outside today.'},
        {en:'Dirty',    es:'Sucio',     e:'1f9fc', ex:'My hands are dirty.'},
        {en:'Clean',    es:'Limpio',    e:'1f6bf', ex:'My room is clean and tidy.'},
        {en:'Tall',     es:'Alto',      e:'1f9cd', ex:'My dad is very tall.'},
        {en:'Short',    es:'Bajo',      e:'1f9d2', ex:'I am the shortest in my class.'},
        {en:'Old',      es:'Viejo',     e:'1f474', ex:'That building is very old.'},
        {en:'New',      es:'Nuevo',     e:'1f381', ex:'I have new trainers!'},
        {en:'Kind',     es:'Amable',    e:'1f970', ex:'My teacher is very kind.'},
        {en:'Brave',    es:'Valiente',  e:'1f9b8', ex:'The firefighter is very brave.'},
        {en:'Clever',   es:'Listo',     e:'1f9e0', ex:'She is very clever at maths.'},
        {en:'Silly',    es:'Tonto',     e:'1f92a', ex:'Stop being silly!'},
        {en:'Loud',     es:'Ruidoso',   e:'1f4e3', ex:'The music is very loud.'},
        {en:'Quiet',    es:'Tranquilo', e:'1f910', ex:'Please be quiet in the library.'},
        {en:'Beautiful',es:'Bonito',    e:'1f338', ex:'The flowers are beautiful.'},
        {en:'Ugly',     es:'Feo',       e:'1f631', ex:'He thinks spiders are ugly.'},
      ]},
    { id: 'school_i', label: 'Colegio', icon: '🏫', color: '#6bcb77',
      items: [
        {en:'School',    es:'Colegio',    e:'1f3eb', ex:'I like going to school.'},
        {en:'Pencil',    es:'Lápiz',      e:'270f',  ex:'I write with my pencil.'},
        {en:'Pen',       es:'Bolígrafo',  e:'1f58a', ex:'I use a pen for my homework.'},
        {en:'Book',      es:'Libro',      e:'1f4da', ex:'I have a new reading book.'},
        {en:'Ruler',     es:'Regla',      e:'1f4cf', ex:'I use a ruler to draw straight lines.'},
        {en:'Scissors',  es:'Tijeras',    e:'2702',  ex:'Be careful with scissors.'},
        {en:'Bag',       es:'Mochila',    e:'1f392', ex:'My school bag is heavy today.'},
        {en:'Rubber',    es:'Goma',       e:'1f9f9', ex:'I use a rubber to erase mistakes.'},
        {en:'Crayon',    es:'Cera',       e:'1f58d', ex:'I colour with crayons.'},
        {en:'Glue',      es:'Pegamento',  e:'1f9f4', ex:'I stick things with glue.'},
        {en:'Map',       es:'Mapa',       e:'1f5fa', ex:'We look at the map in geography.'},
        {en:'Computer',  es:'Ordenador',  e:'1f4bb', ex:'I use the computer for research.'},
        {en:'Teacher',   es:'Profesor',   e:'1f469-200d-1f3eb', ex:'My teacher explains things well.'},
        {en:'Classroom', es:'Clase',      e:'1f4cb', ex:'Our classroom is bright and colourful.'},
        {en:'Homework',  es:'Deberes',    e:'1f4da', ex:'I do my homework after dinner.'},
        {en:'Test',      es:'Examen',     e:'1f4dd', ex:'I have a spelling test today.'},
        {en:'Break time',es:'Recreo',     e:'26bd',  ex:'I play football at break time.'},
        {en:'Library',   es:'Biblioteca', e:'1f4da', ex:'I borrow books from the library.'},
      ]},
    { id: 'transport_i', label: 'Transporte', icon: '🚗', color: '#0ea5e9',
      items: [
        {en:'Car',        es:'Coche',            e:'1f697', ex:'We travel by car.'},
        {en:'Bus',        es:'Autobús',          e:'1f68c', ex:'I take the bus to school.'},
        {en:'Train',      es:'Tren',             e:'1f682', ex:'The train is fast.'},
        {en:'Plane',      es:'Avión',            e:'2708',  ex:'The plane flies very high.'},
        {en:'Boat',       es:'Barco',            e:'26f5',  ex:'We go on a boat trip.'},
        {en:'Bike',       es:'Bicicleta',        e:'1f6b2', ex:'I ride my bike to the park.'},
        {en:'Motorbike',  es:'Moto',             e:'1f3cd', ex:'The motorbike is loud.'},
        {en:'Helicopter', es:'Helicóptero',      e:'1f681', ex:'The helicopter hovers above.'},
        {en:'Rocket',     es:'Cohete',           e:'1f680', ex:'A rocket goes into space.'},
        {en:'Taxi',       es:'Taxi',             e:'1f695', ex:'We took a taxi to the airport.'},
        {en:'Ambulance',  es:'Ambulancia',       e:'1f691', ex:'The ambulance drives very fast.'},
        {en:'Fire truck', es:'Camión bomberos',  e:'1f692', ex:'The fire truck has a big ladder.'},
        {en:'Submarine',  es:'Submarino',        e:'1f6a2', ex:'A submarine goes under the sea.'},
        {en:'Tram',       es:'Tranvía',          e:'1f68a', ex:'The tram runs through the city.'},
      ]},
    { id: 'jobs_i', label: 'Profesiones', icon: '👨‍⚕️', color: '#8b5cf6',
      items: [
        {en:'Doctor',     es:'Médico',      e:'1f469-200d-2695-fe0f', ex:'The doctor helps sick people.'},
        {en:'Teacher',    es:'Profesor',    e:'1f469-200d-1f3eb',     ex:'The teacher explains the lesson.'},
        {en:'Firefighter',es:'Bombero',     e:'1f9d1-200d-1f692',     ex:'The firefighter puts out fires.'},
        {en:'Police',     es:'Policía',     e:'1f46e',                ex:'The police keep us safe.'},
        {en:'Cook',       es:'Cocinero',    e:'1f9d1-200d-1f373',     ex:'The cook makes delicious food.'},
        {en:'Farmer',     es:'Granjero',    e:'1f9d1-200d-1f33e',     ex:'The farmer grows vegetables.'},
        {en:'Pilot',      es:'Piloto',      e:'1f9d1-200d-2708-fe0f', ex:'The pilot flies the aeroplane.'},
        {en:'Vet',        es:'Veterinario', e:'1f9d1-200d-2695-fe0f', ex:'The vet looks after animals.'},
        {en:'Singer',     es:'Cantante',    e:'1f3a4',                ex:'The singer has a beautiful voice.'},
        {en:'Painter',    es:'Pintor',      e:'1f9d1-200d-1f3a8',     ex:'The painter creates art.'},
        {en:'Builder',    es:'Constructor', e:'1f477',                ex:'The builder constructs buildings.'},
        {en:'Driver',     es:'Conductor',   e:'1f9d1-200d-1f692',     ex:'The driver takes us home.'},
        {en:'Nurse',      es:'Enfermero',   e:'1f469-200d-2695-fe0f', ex:'The nurse cares for patients.'},
        {en:'Dentist',    es:'Dentista',    e:'1f9b7',                ex:'The dentist checks my teeth.'},
      ]},
    { id: 'sports_i', label: 'Deportes', icon: '⚽', color: '#f97316',
      items: [
        {en:'Football',   es:'Fútbol',     e:'26bd',  ex:'I play football with my friends.'},
        {en:'Basketball', es:'Baloncesto', e:'1f3c0', ex:'Basketball players are very tall.'},
        {en:'Tennis',     es:'Tenis',      e:'1f3be', ex:'I take tennis lessons.'},
        {en:'Swimming',   es:'Natación',   e:'1f3ca', ex:'Swimming is great exercise.'},
        {en:'Running',    es:'Correr',     e:'1f3c3', ex:'Running keeps you healthy.'},
        {en:'Cycling',    es:'Ciclismo',   e:'1f6b4', ex:'Cycling is good for the planet.'},
        {en:'Gymnastics', es:'Gimnasia',   e:'1f938', ex:'She does gymnastics every week.'},
        {en:'Skiing',     es:'Esquí',      e:'26f7',  ex:'We go skiing in winter.'},
        {en:'Dancing',    es:'Baile',      e:'1f483', ex:'I love dancing to pop music.'},
        {en:'Karate',     es:'Karate',     e:'1f94b', ex:'He has a black belt in karate.'},
        {en:'Volleyball', es:'Voleibol',   e:'1f3d0', ex:'We play volleyball on the beach.'},
        {en:'Baseball',   es:'Béisbol',    e:'26be',  ex:'Baseball is popular in America.'},
      ]},
    { id: 'phrases_inter', label: 'Frases I can', icon: '💪', color: '#ec4899',
      items: [
        {en:'I can swim',               es:'Puedo nadar',               e:'1f3ca', p:true},
        {en:'I can ride a bike',        es:'Puedo montar en bici',      e:'1f6b2', p:true},
        {en:'I can speak English',      es:'Puedo hablar inglés',       e:'1f1ec-1f1e7', p:true},
        {en:'I can count to ten',       es:'Puedo contar hasta diez',   e:'1f51f', p:true},
        {en:'I can play football',      es:'Puedo jugar al fútbol',     e:'26bd', p:true},
        {en:'I cannot fly',             es:'No puedo volar',            e:'1f6eb', p:true},
        {en:'I cannot drive a car',     es:'No puedo conducir un coche',e:'1f697', p:true},
        {en:'Can you help me please?',  es:'¿Puedes ayudarme por favor?',e:'1f91d', p:true},
        {en:'I like playing football',  es:'Me gusta jugar al fútbol',  e:'26bd', p:true},
        {en:'I love reading books',     es:'Me encanta leer libros',    e:'1f4da', p:true},
        {en:'I do not like homework',   es:'No me gustan los deberes',  e:'1f4da', p:true},
        {en:'My favourite sport is swimming',es:'Mi deporte favorito es nadar',e:'1f3ca', p:true},
        {en:'I play football on Saturday',  es:'Juego al fútbol los sábados', e:'26bd', p:true},
        {en:'My teacher is very nice',  es:'Mi profesora es muy simpática',e:'1f469-200d-1f3eb', p:true},
        {en:'I have got a new book',    es:'Tengo un libro nuevo',      e:'1f4da', p:true, tip:'💡 "Have got" = tener. También puedes decir "I have a new book" — ¡es lo mismo!'},
        {en:'She has got blue eyes',    es:'Ella tiene los ojos azules',e:'1f499', p:true, tip:'💡 Con she/he/it usamos "has got", no "have got". ¡Cuidado con la S!'},
        {en:'He has got brown hair',    es:'Él tiene el pelo marrón',   e:'1f9b1', p:true, tip:'💡 "He has got" = "He has" — ambas formas son correctas en inglés'},
        {en:'We are best friends',      es:'Somos mejores amigos',      e:'1f91d', p:true},
        {en:'They are playing outside', es:'Están jugando fuera',       e:'1f3ae', p:true},
        {en:'It is very hot today',     es:'Hoy hace mucho calor',      e:'1f975', p:true},
        {en:'What is the weather like?',es:'¿Cómo está el tiempo?',     e:'2600', p:true},
        {en:'It is cold and windy',     es:'Hace frío y viento',        e:'1f32c', p:true},
        {en:'I am going to the park',   es:'Voy al parque',             e:'1f333', p:true},
        {en:'Let us play together!',    es:'¡Juguemos juntos!',         e:'1f91d', p:true},
        {en:'Well done! That is great!',es:'¡Muy bien! ¡Genial!',       e:'1f44f', p:true},
      ]},
    { id: 'dialogues_inter', label: 'Diálogos', icon: '🗣️', color: '#14b8a6',
      items: [
        {en:'Hello! How are you?',          es:'¡Hola! ¿Cómo estás?',          e:'1f44b', p:true},
        {en:'I am fine, thank you!',        es:'¡Estoy bien, gracias!',         e:'1f600', p:true},
        {en:'What is your name?',           es:'¿Cómo te llamas?',              e:'2753', p:true, tip:'💡 Contracción rápida: "What\'s your name?" Los ingleses la usan siempre en conversación'},
        {en:'My name is Carlos',            es:'Me llamo Carlos',               e:'1f466', p:true},
        {en:'How old are you?',             es:'¿Cuántos años tienes?',         e:'1f382', p:true, tip:'💡 "How old" = qué edad. Respuesta: "I am seven years old"'},
        {en:'I am seven years old',         es:'Tengo siete años',              e:'0037-20e3', p:true},
        {en:'Where do you live?',           es:'¿Dónde vives?',                 e:'1f3e0', p:true},
        {en:'I live in Madrid',             es:'Vivo en Madrid',                e:'1f3e0', p:true},
        {en:'Do you have any brothers or sisters?',es:'¿Tienes hermanos?',      e:'1f46a', p:true},
        {en:'Yes, I have one brother',      es:'Sí, tengo un hermano',          e:'1f466', p:true},
        {en:'No, I am an only child',       es:'No, soy hijo único',            e:'1f9d1', p:true},
        {en:'What do you like doing?',      es:'¿Qué te gusta hacer?',          e:'1f914', p:true},
        {en:'I like playing video games',   es:'Me gusta jugar a videojuegos',  e:'1f3ae', p:true},
        {en:'Me too! That is great!',       es:'¡Yo también! ¡Genial!',         e:'1f44d', p:true},
        {en:'Can I play with you?',         es:'¿Puedo jugar contigo?',         e:'1f91d', p:true},
        {en:'Of course! Come on!',          es:'¡Claro! ¡Vamos!',               e:'1f3c3', p:true},
        {en:'Excuse me, where is the toilet?',es:'Perdona, ¿dónde está el baño?',e:'1f6bd', p:true},
        {en:'It is over there, on the left',es:'Está allí, a la izquierda',     e:'1f4cd', p:true},
        {en:'Thank you very much!',         es:'¡Muchas gracias!',              e:'1f60a', p:true},
        {en:'You are welcome!',             es:'¡De nada!',                     e:'1f44d', p:true},
        {en:'See you tomorrow!',            es:'¡Hasta mañana!',                e:'1f44b', p:true},
        {en:'Have a good day!',             es:'¡Que tengas un buen día!',      e:'2600', p:true},
        {en:'What time is lunch?',          es:'¿A qué hora es la comida?',     e:'1f37d', p:true},
        {en:'It is at one o\'clock',        es:'Es a la una',                   e:'1f550', p:true},
        {en:'I am hungry! What is for lunch?',es:'¡Tengo hambre! ¿Qué hay para comer?',e:'1f974', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // AVANZADO  8–10 años
  // ══════════════════════════════════════════════════════════════
  advanced: [
    { id: 'nature_a', label: 'Naturaleza', icon: '🌿', color: '#6bcb77',
      items: [
        {en:'Forest',    es:'Bosque',    e:'1f333', ex:'The forest is full of tall trees.'},
        {en:'Mountain',  es:'Montaña',   e:'26f0',  ex:'We climbed to the top of the mountain.'},
        {en:'River',     es:'Río',       e:'1f3de', ex:'The river flows to the sea.'},
        {en:'Sea',       es:'Mar',       e:'1f30a', ex:'The sea is deep and blue.'},
        {en:'Beach',     es:'Playa',     e:'1f3d6', ex:'I build sandcastles at the beach.'},
        {en:'Desert',    es:'Desierto',  e:'1f3dc', ex:'The desert is very hot and dry.'},
        {en:'Jungle',    es:'Selva',     e:'1f332', ex:'Many animals live in the jungle.'},
        {en:'Lake',      es:'Lago',      e:'1f3de', ex:'We canoe on the lake.'},
        {en:'Volcano',   es:'Volcán',    e:'1f30b', ex:'The volcano erupted last year.'},
        {en:'Waterfall', es:'Cascada',   e:'1f3de', ex:'The waterfall is spectacular.'},
        {en:'Flower',    es:'Flor',      e:'1f338', ex:'The flower smells beautiful.'},
        {en:'Tree',      es:'Árbol',     e:'1f333', ex:'The oak tree is very old.'},
        {en:'Grass',     es:'Hierba',    e:'1f33f', ex:'The grass is green after the rain.'},
        {en:'Rock',      es:'Roca',      e:'1faa8', ex:'We climbed on the rocks.'},
        {en:'Island',    es:'Isla',      e:'1f334', ex:'The island is surrounded by water.'},
        {en:'Cave',      es:'Cueva',     e:'1f9b7', ex:'Bats live inside the cave.'},
      ]},
    { id: 'wild_animals_a', label: 'Animales salvajes', icon: '🦁', color: '#f97316',
      items: [
        {en:'Tiger',    es:'Tigre',     e:'1f42f', ex:'The tiger is a powerful predator.'},
        {en:'Giraffe',  es:'Jirafa',    e:'1f992', ex:'A giraffe has a very long neck.'},
        {en:'Zebra',    es:'Cebra',     e:'1f993', ex:'The zebra has black and white stripes.'},
        {en:'Gorilla',  es:'Gorila',    e:'1f98d', ex:'Gorillas are very intelligent animals.'},
        {en:'Crocodile',es:'Cocodrilo', e:'1f40a', ex:'The crocodile lies still near the river.'},
        {en:'Penguin',  es:'Pingüino',  e:'1f427', ex:'Penguins live in cold places.'},
        {en:'Dolphin',  es:'Delfín',    e:'1f42c', ex:'Dolphins are very clever mammals.'},
        {en:'Shark',    es:'Tiburón',   e:'1f988', ex:'A shark has very sharp teeth.'},
        {en:'Parrot',   es:'Loro',      e:'1f99c', ex:'The parrot can copy what you say.'},
        {en:'Flamingo', es:'Flamenco',  e:'1f9a9', ex:'The flamingo is bright pink.'},
        {en:'Panda',    es:'Panda',     e:'1f43c', ex:'The giant panda eats bamboo.'},
        {en:'Kangaroo', es:'Canguro',   e:'1f998', ex:'The kangaroo carries its baby in a pouch.'},
        {en:'Owl',      es:'Búho',      e:'1f989', ex:'The owl hunts at night.'},
        {en:'Fox',      es:'Zorro',     e:'1f98a', ex:'The fox is clever and fast.'},
        {en:'Wolf',     es:'Lobo',      e:'1f43a', ex:'Wolves live in packs.'},
        {en:'Snake',    es:'Serpiente', e:'1f40d', ex:'Some snakes can be dangerous.'},
      ]},
    { id: 'seasons_a', label: 'Estaciones y meses', icon: '🍂', color: '#fbbf24',
      items: [
        {en:'Spring',    es:'Primavera', e:'1f338', ex:'In spring, flowers start to bloom.'},
        {en:'Summer',    es:'Verano',    e:'2600',  ex:'In summer it is hot and sunny.'},
        {en:'Autumn',    es:'Otoño',     e:'1f342', ex:'In autumn the leaves turn orange.'},
        {en:'Winter',    es:'Invierno',  e:'2744',  ex:'In winter it is cold and frosty.'},
        {en:'January',   es:'Enero',     e:'1f321', ex:'January is the first month of the year.'},
        {en:'February',  es:'Febrero',   e:'2764',  ex:'February has twenty-eight days.'},
        {en:'March',     es:'Marzo',     e:'1f340', ex:'In March the weather gets warmer.'},
        {en:'April',     es:'Abril',     e:'1f327', ex:'April showers bring May flowers.'},
        {en:'May',       es:'Mayo',      e:'1f33b', ex:'In May we have lots of bank holidays.'},
        {en:'June',      es:'Junio',     e:'2600',  ex:'June is the start of summer.'},
        {en:'July',      es:'Julio',     e:'1f3d6', ex:'July is usually the hottest month.'},
        {en:'August',    es:'Agosto',    e:'1f4a5', ex:'We go on holiday in August.'},
        {en:'September', es:'Septiembre',e:'1f342', ex:'School starts again in September.'},
        {en:'October',   es:'Octubre',   e:'1f383', ex:'Halloween is celebrated in October.'},
        {en:'November',  es:'Noviembre', e:'1f343', ex:'In November the nights are long.'},
        {en:'December',  es:'Diciembre', e:'2744',  ex:'We celebrate Christmas in December.'},
      ]},
    { id: 'daily_routine_a', label: 'Rutinas', icon: '⏰', color: '#4d96ff',
      items: [
        {en:'Wake up',        es:'Despertarse',       e:'1f4a4', p:true},
        {en:'Get dressed',    es:'Vestirse',          e:'1f455', p:true},
        {en:'Brush my teeth', es:'Lavarme los dientes',e:'1fa77', p:true},
        {en:'Have breakfast', es:'Desayunar',         e:'1f373', p:true},
        {en:'Go to school',   es:'Ir al colegio',     e:'1f3eb', p:true},
        {en:'Have lunch',     es:'Almorzar',          e:'1f37d', p:true},
        {en:'Do my homework', es:'Hacer los deberes', e:'1f4da', p:true},
        {en:'Have dinner',    es:'Cenar',             e:'1f372', p:true},
        {en:'Have a shower',  es:'Ducharme',          e:'1f6bf', p:true},
        {en:'Go to bed',      es:'Ir a dormir',       e:'1f6cf', p:true},
        {en:'I usually wake up at seven',es:'Normalmente me despierto a las siete',e:'1f550', p:true},
        {en:'I have breakfast at half past seven',es:'Desayuno a las siete y media',e:'1f373', p:true},
      ]},
    { id: 'conv_greetings_a', label: 'Conversaciones: Saludos', icon: '🤝', color: '#ff6b9d',
      items: [
        {en:'Hi! How are you doing?',          es:'¡Hola! ¿Cómo te va?',               e:'1f44b', p:true},
        {en:'I am doing great, thanks!',       es:'¡Muy bien, gracias!',                e:'1f600', p:true},
        {en:'Not bad, a bit tired though',     es:'Bien, aunque un poco cansado',       e:'1f971', p:true},
        {en:'Nice to meet you!',               es:'¡Encantado de conocerte!',           e:'1f91d', p:true},
        {en:'The pleasure is mine!',           es:'¡El placer es mío!',                 e:'1f60a', p:true},
        {en:'It is good to see you again!',    es:'¡Me alegra verte de nuevo!',         e:'1f604', p:true},
        {en:'I have not seen you for ages!',   es:'¡Hace siglos que no te veo!',        e:'1f635', p:true},
        {en:'How was your weekend?',           es:'¿Qué tal el fin de semana?',         e:'1f389', p:true},
        {en:'It was fantastic! We went to the beach.',es:'¡Fue fantástico! Fuimos a la playa.',e:'1f3d6', p:true},
        {en:'That sounds amazing!',            es:'¡Eso suena genial!',                 e:'1f929', p:true},
        {en:'See you later!',                  es:'¡Hasta luego!',                      e:'1f44b', p:true},
        {en:'Take care!',                      es:'¡Cuídate!',                          e:'1f496', p:true},
        {en:'Have a great time!',              es:'¡Que lo pases bien!',                e:'1f389', p:true},
        {en:'Good luck with your test!',       es:'¡Buena suerte en el examen!',        e:'1f340', p:true},
        {en:'Fingers crossed!',                es:'¡Crucemos los dedos!',               e:'1f91e', p:true},
      ]},
    { id: 'conv_school_a', label: 'Conversaciones: Colegio', icon: '🏫', color: '#6bcb77',
      items: [
        {en:'What subjects do you like?',      es:'¿Qué asignaturas te gustan?',        e:'1f4da', p:true},
        {en:'I love Maths and Science',        es:'Me encantan Mates y Ciencias',       e:'1f9ea', p:true},
        {en:'I find English a bit difficult',  es:'El inglés se me hace un poco difícil',e:'1f1ec-1f1e7', p:true},
        {en:'Do not worry, practice makes perfect!',es:'¡No te preocupes, la práctica hace al maestro!',e:'1f4aa', p:true},
        {en:'Can you repeat that please?',     es:'¿Puedes repetirlo por favor?',       e:'1f501', p:true, tip:'💡 "Can" = poder. "Could you repeat that?" suena incluso más educado'},
        {en:'I do not understand',             es:'No entiendo',                        e:'1f615', p:true},
        {en:'Could you speak more slowly?',    es:'¿Podrías hablar más despacio?',      e:'1f422', p:true, tip:'💡 "Could" es más formal y educado que "can" — úsalo cuando pidas un favor importante'},
        {en:'How do you spell that?',          es:'¿Cómo se escribe?',                  e:'270f', p:true},
        {en:'What does this word mean?',       es:'¿Qué significa esta palabra?',       e:'2753', p:true},
        {en:'I got ten out of ten!',           es:'¡Saqué un diez!',                    e:'1f4af', p:true},
        {en:'I passed my English test!',       es:'¡Aprobé el examen de inglés!',       e:'1f389', p:true},
        {en:'We have got a school trip tomorrow',es:'Mañana tenemos una excursión',     e:'1f68c', p:true},
        {en:'I am really excited!',            es:'¡Estoy muy emocionado!',             e:'1f929', p:true},
        {en:'Our teacher is so funny!',        es:'¡Nuestra profe es muy graciosa!',    e:'1f602', p:true},
        {en:'I finished my homework early',    es:'Terminé los deberes pronto',         e:'1f44d', p:true},
      ]},
    { id: 'conv_family_a', label: 'Conversaciones: Familia', icon: '👨‍👩‍👧', color: '#8b5cf6',
      items: [
        {en:'Tell me about your family',       es:'Háblame de tu familia',              e:'1f46a', p:true},
        {en:'I have got a big family',         es:'Tengo una familia grande',           e:'1f46a', p:true},
        {en:'There are five of us at home',    es:'En casa somos cinco',                e:'1f3e0', p:true},
        {en:'My mum works as a doctor',        es:'Mi mamá trabaja de médico',          e:'1f469-200d-2695-fe0f', p:true},
        {en:'My dad is a teacher',             es:'Mi papá es profesor',                e:'1f468-200d-1f3eb', p:true},
        {en:'My grandparents live nearby',     es:'Mis abuelos viven cerca',            e:'1f475', p:true},
        {en:'We visit them every Sunday',      es:'Los visitamos cada domingo',         e:'26ea', p:true},
        {en:'My brother is older than me',     es:'Mi hermano es mayor que yo',         e:'1f466', p:true},
        {en:'My sister is two years younger',  es:'Mi hermana es dos años menor',       e:'1f467', p:true},
        {en:'We sometimes argue but we love each other',es:'A veces discutimos pero nos queremos mucho',e:'2764', p:true},
        {en:'My mum makes the best food!',     es:'¡Mi mamá hace la mejor comida!',     e:'1f373', p:true},
        {en:'We go on holiday together in summer',es:'En verano nos vamos de vacaciones juntos',e:'2600', p:true},
        {en:'Last year we went to the beach',  es:'El año pasado fuimos a la playa',    e:'1f3d6', p:true},
        {en:'It was the best holiday ever!',   es:'¡Fueron las mejores vacaciones!',    e:'1f929', p:true},
        {en:'I am lucky to have my family',    es:'Soy afortunado de tener mi familia', e:'2764', p:true},
      ]},
    { id: 'conv_hobbies_a', label: 'Conversaciones: Aficiones', icon: '🎸', color: '#ef4444',
      items: [
        {en:'What are your hobbies?',          es:'¿Cuáles son tus aficiones?',         e:'1f3ae', p:true},
        {en:'I really enjoy playing the guitar',es:'Me encanta tocar la guitarra',      e:'1f3b8', p:true},
        {en:'I have been playing for two years',es:'Llevo tocando dos años',            e:'1f3b5', p:true},
        {en:'I am also into drawing',          es:'También me gusta dibujar',           e:'1f58c', p:true},
        {en:'I draw comics in my free time',   es:'Dibujo cómics en mi tiempo libre',   e:'1f4d6', p:true},
        {en:'That is so cool!',                es:'¡Eso mola mucho!',                   e:'1f60e', p:true},
        {en:'Do you play any sports?',         es:'¿Practicas algún deporte?',          e:'26bd', p:true},
        {en:'I play football twice a week',    es:'Juego al fútbol dos veces a la semana',e:'26bd', p:true},
        {en:'My favourite team is Real Madrid',es:'Mi equipo favorito es el Real Madrid',e:'26bd', p:true},
        {en:'Who is your favourite player?',   es:'¿Quién es tu jugador favorito?',     e:'1f3c6', p:true},
        {en:'I also like watching films',      es:'También me gusta ver películas',     e:'1f3ac', p:true},
        {en:'What kind of films do you prefer?',es:'¿Qué tipo de películas prefieres?', e:'1f37f', p:true},
        {en:'I prefer adventure and comedy films',es:'Prefiero películas de aventuras y comedia',e:'1f3ac', p:true},
        {en:'Have you seen the new Marvel film?',es:'¿Has visto la nueva película de Marvel?',e:'1f9b8', p:true},
        {en:'Yes! It was absolutely brilliant!',es:'¡Sí! ¡Fue absolutamente brillante!',e:'1f929', p:true},
      ]},
    { id: 'conv_town_a', label: 'Conversaciones: Ciudad', icon: '🏙️', color: '#0ea5e9',
      items: [
        {en:'Excuse me, can you help me?',     es:'Perdona, ¿puedes ayudarme?',         e:'1f91d', p:true},
        {en:'Of course! What do you need?',    es:'¡Claro! ¿Qué necesitas?',            e:'1f604', p:true},
        {en:'How do I get to the park?',       es:'¿Cómo llego al parque?',             e:'1f333', p:true},
        {en:'Go straight on and turn left',    es:'Sigue recto y gira a la izquierda',  e:'1f4cd', p:true},
        {en:'Is it far from here?',            es:'¿Está lejos de aquí?',               e:'1f4cd', p:true},
        {en:'No, it is about five minutes away',es:'No, está a unos cinco minutos',     e:'1f552', p:true},
        {en:'Thank you so much!',              es:'¡Muchas gracias!',                   e:'1f60a', p:true},
        {en:'No problem, enjoy your day!',     es:'¡Sin problema, que disfrutes el día!',e:'2600', p:true},
        {en:'Where is the nearest supermarket?',es:'¿Dónde está el supermercado más cercano?',e:'1f6d2', p:true},
        {en:'There is one just around the corner',es:'Hay uno justo a la vuelta de la esquina',e:'1f3ea', p:true},
        {en:'I would like to buy a sandwich please',es:'Quisiera comprar un bocadillo por favor',e:'1f96a', p:true},
        {en:'That will be two pounds fifty',   es:'Son dos libras y cincuenta peniques', e:'1f4b0', p:true},
        {en:'Here you are. Keep the change!',  es:'Aquí tiene. ¡Quédese el cambio!',    e:'1f4b5', p:true},
        {en:'The park is beautiful in spring', es:'El parque es precioso en primavera', e:'1f338', p:true},
        {en:'I love this city!',               es:'¡Me encanta esta ciudad!',           e:'1f3d9', p:true},
      ]},
    { id: 'sentences_a', label: 'Frases completas', icon: '🗣️', color: '#c77dff',
      items: [
        {en:'I go to school every day',            es:'Voy al colegio cada día',            e:'1f3eb', p:true, tip:'💡 Present Simple: para rutinas habituales. I go, you go, he/she GOES (¡con S!)'},
        {en:'My favourite colour is blue',         es:'Mi color favorito es el azul',       e:'1f499', p:true},
        {en:'I have two sisters and one brother',  es:'Tengo dos hermanas y un hermano',    e:'1f46a', p:true},
        {en:'I live in a big house near the park', es:'Vivo en una casa grande cerca del parque',e:'1f3e0', p:true},
        {en:'I can speak English and Spanish',     es:'Puedo hablar inglés y español',      e:'1f1ec-1f1e7', p:true},
        {en:'I like playing football on Sundays',  es:'Me gusta jugar al fútbol los domingos',e:'26bd', p:true},
        {en:'She is my best friend in the world',  es:'Ella es mi mejor amiga del mundo',   e:'1f91d', p:true},
        {en:'It is a beautiful sunny day today',   es:'Hoy es un día bonito y soleado',     e:'2600', p:true},
        {en:'The cat is sleeping on the sofa',     es:'El gato está durmiendo en el sofá',  e:'1f431', p:true},
        {en:'We are going on holiday next week',   es:'Nos vamos de vacaciones la semana que viene',e:'1f334', p:true, tip:'💡 "Going to" + planes futuros concretos. "Are going on" = Present Continuous para planes'},
        {en:'I would like to be a doctor when I grow up',es:'Quiero ser médico cuando sea mayor',e:'1f469-200d-2695-fe0f', p:true},
        {en:'Last summer we visited London',       es:'El verano pasado visitamos Londres', e:'1f1ec-1f1e7', p:true, tip:'💡 Past Simple: "visited" = visit + ED. "Last" siempre va con tiempo pasado'},
        {en:'In London it rained every day!',      es:'¡En Londres llovió todos los días!', e:'1f327', p:true},
        {en:'I think animals should be free',      es:'Creo que los animales deben ser libres',e:'1f98b', p:true},
        {en:'It is important to look after our planet',es:'Es importante cuidar nuestro planeta',e:'1f30d', p:true},
        {en:'Reading books makes you smarter',     es:'Leer libros te hace más listo',      e:'1f4da', p:true},
        {en:'I am going to study hard this year',  es:'Este año voy a estudiar mucho',      e:'1f4da', p:true},
        {en:'My dream is to travel around the world',es:'Mi sueño es viajar por el mundo',  e:'1f30d', p:true},
        {en:'English is useful for travelling',    es:'El inglés es útil para viajar',      e:'2708', p:true},
        {en:'Practice every day and you will improve',es:'Practica cada día y mejorarás',   e:'1f4aa', p:true},
      ]},
  ],
};

// ══════════════════════════════════════════════════════════════
// CANCIONES / NURSERY RHYMES
// ══════════════════════════════════════════════════════════════
const SONGS = [
  {
    id: 'twinkle', title: 'Twinkle Twinkle', icon: '⭐', age: '3–6',
    color: '#4d96ff',
    lines: [
      { text: 'Twinkle, twinkle, little star',    es: 'Brilla, brilla, estrellita' },
      { text: 'How I wonder what you are',         es: '¿Qué eres tú, me pregunto yo?' },
      { text: 'Up above the world so high',        es: 'Allá arriba, en el cielo' },
      { text: 'Like a diamond in the sky',         es: 'Como un diamante brillando' },
      { text: 'Twinkle, twinkle, little star',    es: 'Brilla, brilla, estrellita' },
      { text: 'How I wonder what you are',         es: '¿Qué eres tú, me pregunto yo?' },
    ]
  },
  {
    id: 'head_shoulders', title: 'Head, Shoulders, Knees and Toes', icon: '🙆', age: '3–6',
    color: '#ff6b9d',
    lines: [
      { text: 'Head, shoulders, knees and toes',  es: 'Cabeza, hombros, rodillas y pies' },
      { text: 'Knees and toes',                    es: 'Rodillas y pies' },
      { text: 'Head, shoulders, knees and toes',  es: 'Cabeza, hombros, rodillas y pies' },
      { text: 'Eyes and ears and mouth and nose',  es: 'Ojos, orejas, boca y nariz' },
      { text: 'Head, shoulders, knees and toes',  es: 'Cabeza, hombros, rodillas y pies' },
      { text: 'Knees and toes',                    es: 'Rodillas y pies' },
    ]
  },
  {
    id: 'old_macdonald', title: 'Old MacDonald Had a Farm', icon: '🚜', age: '3–7',
    color: '#6bcb77',
    lines: [
      { text: 'Old MacDonald had a farm, E-I-E-I-O', es: 'El viejo MacDonald tenía una granja' },
      { text: 'And on his farm he had a cow, E-I-E-I-O', es: 'Y en esa granja había una vaca' },
      { text: 'With a moo moo here and a moo moo there', es: 'Con un mu mu aquí y un mu mu allá' },
      { text: 'Here a moo, there a moo, everywhere a moo moo', es: 'Aquí un mu, allá un mu, por todas partes mu mu' },
      { text: 'Old MacDonald had a farm, E-I-E-I-O', es: 'El viejo MacDonald tenía una granja' },
    ]
  },
  {
    id: 'if_youre_happy', title: "If You're Happy", icon: '😊', age: '3–7',
    color: '#ffd93d',
    lines: [
      { text: "If you're happy and you know it, clap your hands", es: 'Si estás feliz y lo sabes, da palmadas' },
      { text: "If you're happy and you know it, clap your hands", es: 'Si estás feliz y lo sabes, da palmadas' },
      { text: "If you're happy and you know it, then your face will surely show it", es: 'Si estás feliz y lo sabes, tu cara lo demostrará' },
      { text: "If you're happy and you know it, clap your hands", es: 'Si estás feliz y lo sabes, da palmadas' },
    ]
  },
  {
    id: 'wheels_bus', title: 'The Wheels on the Bus', icon: '🚌', age: '3–7',
    color: '#f97316',
    lines: [
      { text: 'The wheels on the bus go round and round', es: 'Las ruedas del autobús dan vueltas y vueltas' },
      { text: 'Round and round, round and round',          es: 'Vueltas y vueltas, vueltas y vueltas' },
      { text: 'The wheels on the bus go round and round',  es: 'Las ruedas del autobús dan vueltas y vueltas' },
      { text: 'All through the town',                      es: 'Por toda la ciudad' },
      { text: 'The driver on the bus says move on back',   es: 'El conductor dice: ¡moverse atrás!' },
      { text: 'The babies on the bus say wah wah wah',     es: 'Los bebés del autobús lloran: ¡buaaa!' },
    ]
  },
  {
    id: 'abc_song', title: 'ABC Song', icon: '🔤', age: '4–7',
    color: '#c77dff',
    lines: [
      { text: 'A B C D E F G',              es: 'A B C D E F G' },
      { text: 'H I J K L M N O P',          es: 'H I J K L M N O P' },
      { text: 'Q R S',                       es: 'Q R S' },
      { text: 'T U V',                       es: 'T U V' },
      { text: 'W X Y and Z',                 es: 'W X Y y Z' },
      { text: 'Now I know my ABCs',          es: 'Ya sé el abecedario' },
      { text: 'Next time won\'t you sing with me?', es: '¿La próxima vez cantarás conmigo?' },
    ]
  },
  {
    id: 'five_little_ducks', title: 'Five Little Ducks', icon: '🦆', age: '3–6',
    color: '#14b8a6',
    lines: [
      { text: 'Five little ducks went out one day',        es: 'Cinco patitos salieron un día' },
      { text: 'Over the hills and far away',               es: 'Más allá de las colinas' },
      { text: 'Mother duck said quack quack quack quack',  es: 'La mamá pata dijo: cuac cuac cuac' },
      { text: 'But only four little ducks came back',      es: 'Pero solo cuatro patitos volvieron' },
    ]
  },
  {
    id: 'row_row_row', title: 'Row, Row, Row Your Boat', icon: '🚣', age: '4–7',
    color: '#0ea5e9',
    lines: [
      { text: 'Row, row, row your boat',         es: 'Rema, rema, rema tu barca' },
      { text: 'Gently down the stream',          es: 'Suavemente río abajo' },
      { text: 'Merrily, merrily, merrily, merrily', es: 'Alegremente, alegremente' },
      { text: 'Life is but a dream',             es: 'La vida es solo un sueño' },
    ]
  },
];

// ══════════════════════════════════════════════════════════════
// BADGES
// ══════════════════════════════════════════════════════════════
const BADGES = [
  // Palabras pronunciadas
  { id: 'first_word',   icon: '🌟', label: 'Primera Palabra',  desc: 'Di tu primera palabra en inglés',      threshold: 1,   type: 'words' },
  { id: 'five_words',   icon: '🔥', label: '5 Palabras',       desc: 'Pronunciaste 5 palabras correctas',    threshold: 5,   type: 'words' },
  { id: 'ten_words',    icon: '💪', label: '10 Palabras',      desc: '¡10 palabras dominadas!',              threshold: 10,  type: 'words' },
  { id: 'twenty_five',  icon: '🏆', label: '25 Palabras',      desc: '25 palabras correctas en total',       threshold: 25,  type: 'words' },
  { id: 'fifty',        icon: '👑', label: '50 Palabras',      desc: '50 palabras pronunciadas',             threshold: 50,  type: 'words' },
  { id: 'hundred',      icon: '💯', label: '¡100 Palabras!',   desc: '100 palabras correctas',               threshold: 100, type: 'words' },
  { id: 'two_hundred',  icon: '🚀', label: '200 Palabras',     desc: '200 palabras pronunciadas',            threshold: 200, type: 'words' },
  { id: 'three_hundred',icon: '🌈', label: '300 Palabras',     desc: '300 palabras pronunciadas',            threshold: 300, type: 'words' },
  { id: 'five_hundred', icon: '🦁', label: '¡500 Palabras!',   desc: '¡Casi todo el vocabulario!',           threshold: 500, type: 'words' },
  // Quizzes
  { id: 'first_quiz',   icon: '🎯', label: 'Primer Quiz',      desc: 'Completaste tu primer quiz',           threshold: 1,   type: 'quizzes' },
  { id: 'quiz_master',  icon: '🧠', label: 'Quiz Master',      desc: '5 quizzes completados',                threshold: 5,   type: 'quizzes' },
  { id: 'quiz_pro',     icon: '🎓', label: 'Quiz Pro',         desc: '10 quizzes completados',               threshold: 10,  type: 'quizzes' },
  { id: 'quiz_legend',  icon: '🏅', label: 'Quiz Leyenda',     desc: '25 quizzes completados',               threshold: 25,  type: 'quizzes' },
  // Quiz perfecto
  { id: 'perfect_quiz', icon: '💎', label: 'Quiz Perfecto',    desc: '10/10 en un quiz',                     threshold: 1,   type: 'perfectQuizzes' },
  { id: 'perfect_3',    icon: '💎💎', label: 'Perfecto x3',     desc: '3 quizzes perfectos',                  threshold: 3,   type: 'perfectQuizzes' },
  { id: 'perfect_10',   icon: '✨', label: '10 Perfectos',     desc: '10 quizzes perfectos — ¡increíble!',   threshold: 10,  type: 'perfectQuizzes' },
  // Escritura
  { id: 'first_write',  icon: '✏️', label: 'Primer Trazo',     desc: 'Escribiste tu primera palabra',        threshold: 1,   type: 'wordsWritten' },
  { id: 'write_ten',    icon: '📝', label: 'Escritor',         desc: '10 palabras escritas correctamente',   threshold: 10,  type: 'wordsWritten' },
  { id: 'write_fifty',  icon: '📖', label: 'Gran Escritor',    desc: '50 palabras escritas',                 threshold: 50,  type: 'wordsWritten' },
  { id: 'write_hundred',icon: '📚', label: 'Escritor Pro',     desc: '100 palabras escritas',                threshold: 100, type: 'wordsWritten' },
  { id: 'write_two_hundred',icon: '🖊️', label: 'Maestro Escritor', desc: '200 palabras escritas',            threshold: 200, type: 'wordsWritten' },
  // Modo Dúo
  { id: 'duo_win',      icon: '🆚', label: '¡Ganador Dúo!',   desc: 'Ganaste una partida multijugador',     threshold: 1,   type: 'duoWins' },
  { id: 'duo_five',     icon: '🎮', label: 'Jugador Dúo x5',  desc: '5 partidas dúo ganadas',               threshold: 5,   type: 'duoWins' },
  { id: 'duo_ten',      icon: '🕹️', label: 'Campeón Dúo',    desc: '10 partidas dúo ganadas',              threshold: 10,  type: 'duoWins' },
  { id: 'duo_twenty',   icon: '🏆', label: 'Leyenda Dúo',     desc: '20 partidas dúo ganadas',              threshold: 20,  type: 'duoWins' },
  // Racha
  { id: 'streak_3',     icon: '⚡', label: 'Racha x3',        desc: '3 días seguidos practicando',          threshold: 3,   type: 'streak' },
  { id: 'streak_7',     icon: '🌈', label: 'Semana Completa', desc: '7 días seguidos practicando',          threshold: 7,   type: 'streak' },
  { id: 'streak_14',    icon: '🔥', label: '2 Semanas',       desc: '14 días seguidos practicando',         threshold: 14,  type: 'streak' },
  { id: 'streak_30',    icon: '🌟', label: '1 Mes',           desc: '30 días seguidos — ¡increíble!',       threshold: 30,  type: 'streak' },
  // Palabras dominadas (SRS)
  { id: 'mastered_10',  icon: '🧩', label: '10 Dominadas',    desc: '10 palabras completamente dominadas',  threshold: 10,  type: 'masteredWords' },
  { id: 'mastered_50',  icon: '🎪', label: '50 Dominadas',    desc: '50 palabras completamente dominadas',  threshold: 50,  type: 'masteredWords' },
  { id: 'mastered_100', icon: '🏰', label: '100 Dominadas',   desc: '100 palabras completamente dominadas', threshold: 100, type: 'masteredWords' },
  { id: 'mastered_200', icon: '🌍', label: '200 Dominadas',   desc: '200 palabras completamente dominadas', threshold: 200, type: 'masteredWords' },
  // Canciones
  { id: 'first_song',   icon: '🎵', label: 'Primera Canción', desc: 'Cantaste tu primera canción',          threshold: 1,   type: 'songs' },
  { id: 'song_five',    icon: '🎤', label: 'Cantante',        desc: 'Cantaste 5 canciones completas',       threshold: 5,   type: 'songs' },
];

const AVATARS = ['🦁','🐯','🦊','🐸','🐼','🦄','🐲','🐺','🦋','🐬','🦅','🐧','🦒','🐘','🦈','🐙'];

// ══════════════════════════════════════════════════════════════
// SRS — Spaced Repetition System
// Una palabra se "domina" tras 3 aciertos en días distintos
// ══════════════════════════════════════════════════════════════
function updateWordSRS(state, wordKey) {
  const today = new Date().toDateString();
  const prev = (state.wordAttempts || {})[wordKey] || { count: 0, dates: [] };
  if (prev.dates.includes(today)) return {};
  const newDates = [...prev.dates, today];
  const newCount = prev.count + 1;
  const newWordAttempts = { ...(state.wordAttempts || {}), [wordKey]: { count: newCount, dates: newDates } };
  const newMasteredWords = newCount >= 3
    ? { ...(state.masteredWords || {}), [wordKey]: true }
    : (state.masteredWords || {});
  return { wordAttempts: newWordAttempts, masteredWords: newMasteredWords };
}

function getMasteredCount(state) {
  return Object.keys(state.masteredWords || {}).length;
}

function getWordSRSLevel(state, wordKey) {
  const att = (state.wordAttempts || {})[wordKey];
  if (!att) return 0;
  return Math.min(att.count, 3);
}

function checkBadges(state) {
  const badges = [...(state.unlockedBadges || [])];
  for (const b of BADGES) {
    if (badges.includes(b.id)) continue;
    let val = 0;
    if      (b.type === 'words')         val = state.wordsCorrect     || 0;
    else if (b.type === 'quizzes')       val = state.quizzesCompleted || 0;
    else if (b.type === 'perfectQuizzes')val = state.perfectQuizzes   || 0;
    else if (b.type === 'wordsWritten')  val = state.wordsWritten     || 0;
    else if (b.type === 'duoWins')       val = state.duoWins          || 0;
    else if (b.type === 'streak')        val = state.streak           || 0;
    else if (b.type === 'masteredWords') val = getMasteredCount(state);
    else if (b.type === 'songs')         val = state.songsCompleted   || 0;
    if (val >= b.threshold) badges.push(b.id);
  }
  return badges;
}

function loadState() {
  const defaults = {
    avatar: '🦁', name: '', xp: 0,
    wordsCorrect: 0, quizzesCompleted: 0, perfectQuizzes: 0,
    wordsWritten: 0, duoWins: 0, streak: 0, lastDate: null,
    unlockedBadges: [], learnedWords: {},
    wordAttempts: {}, masteredWords: {},
    selectedVoiceName: null, songsCompleted: 0,
  };
  try {
    const s = localStorage.getItem('englishkids_v3');
    if (s) return { ...defaults, ...JSON.parse(s) };
  } catch(e) {}
  return defaults;
}

function saveState(state) {
  try { localStorage.setItem('englishkids_v3', JSON.stringify(state)); } catch(e) {}
}

function getPlayerLevel(xp) {
  const lvls = [
    { lvl:1,  min:0,     label:'Principiante', color:'#6bcb77' },
    { lvl:2,  min:100,   label:'Aprendiz',     color:'#4d96ff' },
    { lvl:3,  min:300,   label:'Explorador',   color:'#c77dff' },
    { lvl:4,  min:600,   label:'Aventurero',   color:'#ffd93d' },
    { lvl:5,  min:1000,  label:'Campeón',      color:'#ff6b9d' },
    { lvl:6,  min:1500,  label:'Maestro',      color:'#ff6b6b' },
    { lvl:7,  min:2500,  label:'Experto',      color:'#f97316' },
    { lvl:8,  min:4000,  label:'Sabio',        color:'#8b5cf6' },
    { lvl:9,  min:6500,  label:'Superestrella',color:'#ec4899' },
    { lvl:10, min:10000, label:'Leyenda',      color:'#fbbf24' },
  ];
  let cur = lvls[0];
  for (const l of lvls) { if (xp >= l.min) cur = l; else break; }
  const next = lvls[lvls.indexOf(cur)+1];
  const pct  = next ? ((xp - cur.min)/(next.min - cur.min))*100 : 100;
  return { ...cur, next, pct };
}

Object.assign(window, {
  LEVELS, CATEGORIES, BADGES, AVATARS, SONGS,
  checkBadges, loadState, saveState, getPlayerLevel,
  updateWordSRS, getMasteredCount, getWordSRSLevel,
});
