// ─── ENGLISH KIDS — COMPLETE CURRICULUM DATA v3 ──────────────────
// 4 levels · ~600+ words, phrases & dialogues · Age 3–10

const LEVELS = [
  { id: 'starter',      label: 'Starter',     age: '3–4',  stars: 1, color: '#ff6b9d', icon: '🌱' },
  { id: 'basic',        label: 'Básico',      age: '4–6',  stars: 2, color: '#ffd93d', icon: '🌿' },
  { id: 'intermediate', label: 'Intermedio',  age: '6–8',  stars: 3, color: '#4d96ff', icon: '🌳' },
  { id: 'advanced',     label: 'Avanzado',    age: '8–10', stars: 4, color: '#c77dff', icon: '🏆' },
];

const CATEGORIES = {
  // ══════════════════════════════════════════════════════════════
  // STARTER  3–4 años
  // ══════════════════════════════════════════════════════════════
  starter: [
    { id: 'animals_s', label: 'Animales', icon: '🐾', color: '#ff6b6b',
      items: [
        {en:'Cat',     es:'Gato',      e:'1f431'}, {en:'Dog',      es:'Perro',     e:'1f436'},
        {en:'Bird',    es:'Pájaro',    e:'1f426'}, {en:'Fish',     es:'Pez',       e:'1f41f'},
        {en:'Rabbit',  es:'Conejo',    e:'1f430'}, {en:'Bear',     es:'Oso',       e:'1f43b'},
        {en:'Lion',    es:'León',      e:'1f981'}, {en:'Duck',     es:'Pato',      e:'1f986'},
        {en:'Frog',    es:'Rana',      e:'1f438'}, {en:'Cow',      es:'Vaca',      e:'1f404'},
        {en:'Horse',   es:'Caballo',   e:'1f434'}, {en:'Pig',      es:'Cerdo',     e:'1f437'},
        {en:'Sheep',   es:'Oveja',     e:'1f411'}, {en:'Chicken',  es:'Pollo',     e:'1f414'},
        {en:'Elephant',es:'Elefante',  e:'1f418'}, {en:'Monkey',   es:'Mono',      e:'1f412'},
        {en:'Tiger',   es:'Tigre',     e:'1f42f'}, {en:'Penguin',  es:'Pingüino',  e:'1f427'},
      ]},
    { id: 'colors_s', label: 'Colores', icon: '🌈', color: '#fbbf24',
      items: [
        {en:'Red',     es:'Rojo',      e:'2764'},  {en:'Blue',     es:'Azul',      e:'1f499'},
        {en:'Yellow',  es:'Amarillo',  e:'1f49b'}, {en:'Green',    es:'Verde',     e:'1f49a'},
        {en:'Orange',  es:'Naranja',   e:'1f9e1'}, {en:'Pink',     es:'Rosa',      e:'1f497'},
        {en:'Purple',  es:'Morado',    e:'1f49c'}, {en:'White',    es:'Blanco',    e:'1f90d'},
        {en:'Black',   es:'Negro',     e:'1f5a4'}, {en:'Brown',    es:'Marrón',    e:'1f7eb'},
      ]},
    { id: 'fruits_s', label: 'Frutas', icon: '🍎', color: '#6bcb77',
      items: [
        {en:'Apple',      es:'Manzana',   e:'1f34e'}, {en:'Banana',    es:'Plátano',  e:'1f34c'},
        {en:'Orange',     es:'Naranja',   e:'1f34a'}, {en:'Strawberry',es:'Fresa',    e:'1f353'},
        {en:'Grapes',     es:'Uvas',      e:'1f347'}, {en:'Watermelon',es:'Sandía',   e:'1f349'},
        {en:'Peach',      es:'Melocotón', e:'1f351'}, {en:'Pear',      es:'Pera',     e:'1f350'},
        {en:'Cherry',     es:'Cereza',    e:'1f352'}, {en:'Lemon',     es:'Limón',    e:'1f34b'},
        {en:'Mango',      es:'Mango',     e:'1f96d'}, {en:'Pineapple', es:'Piña',     e:'1f34d'},
      ]},
    { id: 'numbers_s', label: 'Números', icon: '🔢', color: '#4d96ff',
      items: [
        {en:'One',   es:'Uno',    e:'0031-20e3'}, {en:'Two',   es:'Dos',    e:'0032-20e3'},
        {en:'Three', es:'Tres',   e:'0033-20e3'}, {en:'Four',  es:'Cuatro', e:'0034-20e3'},
        {en:'Five',  es:'Cinco',  e:'0035-20e3'}, {en:'Six',   es:'Seis',   e:'0036-20e3'},
        {en:'Seven', es:'Siete',  e:'0037-20e3'}, {en:'Eight', es:'Ocho',   e:'0038-20e3'},
        {en:'Nine',  es:'Nueve',  e:'0039-20e3'}, {en:'Ten',   es:'Diez',   e:'1f51f'},
      ]},
    { id: 'body_s', label: 'Cuerpo', icon: '👁️', color: '#f97316',
      items: [
        {en:'Head',   es:'Cabeza',  e:'1f9e0'}, {en:'Eye',    es:'Ojo',     e:'1f441'},
        {en:'Nose',   es:'Nariz',   e:'1f443'}, {en:'Mouth',  es:'Boca',    e:'1f444'},
        {en:'Ear',    es:'Oreja',   e:'1f442'}, {en:'Hand',   es:'Mano',    e:'1f91a'},
        {en:'Foot',   es:'Pie',     e:'1f9b6'}, {en:'Leg',    es:'Pierna',  e:'1f9b5'},
        {en:'Arm',    es:'Brazo',   e:'1f4aa'}, {en:'Hair',   es:'Pelo',    e:'1f9b1'},
        {en:'Teeth',  es:'Dientes', e:'1f9b7'}, {en:'Tongue', es:'Lengua',  e:'1f445'},
        {en:'Tummy',  es:'Barriga', e:'1f7e1'}, {en:'Back',   es:'Espalda', e:'1f9b4'},
      ]},
    { id: 'shapes_s', label: 'Formas', icon: '🔷', color: '#14b8a6',
      items: [
        {en:'Circle',    es:'Círculo',   e:'2b55'},  {en:'Square',    es:'Cuadrado',  e:'1f7e5'},
        {en:'Triangle',  es:'Triángulo', e:'1f53a'}, {en:'Star',      es:'Estrella',  e:'2b50'},
        {en:'Heart',     es:'Corazón',   e:'2764'},  {en:'Diamond',   es:'Diamante',  e:'1f4a0'},
        {en:'Rectangle', es:'Rectángulo',e:'1f7e6'}, {en:'Oval',      es:'Óvalo',     e:'1f48a'},
      ]},
    { id: 'greetings_s', label: 'Saludos', icon: '👋', color: '#c77dff',
      items: [
        {en:'Hello',      es:'Hola',          e:'1f44b'}, {en:'Goodbye',    es:'Adiós',        e:'1f44d'},
        {en:'Please',     es:'Por favor',      e:'1f64f'}, {en:'Thank you',  es:'Gracias',      e:'1f60a'},
        {en:'Yes',        es:'Sí',             e:'2705'},  {en:'No',         es:'No',           e:'274c'},
        {en:'Sorry',      es:'Lo siento',      e:'1f972'}, {en:'Good morning',es:'Buenos días', e:'1f305'},
        {en:'Good night', es:'Buenas noches',  e:'1f319'}, {en:'Good afternoon',es:'Buenas tardes',e:'1f31e'},
      ]},
    { id: 'phrases_starter', label: 'Mis frases', icon: '💬', color: '#ff6b9d',
      items: [
        {en:'My name is...',         es:'Me llamo...',           e:'1f476', p:true},
        {en:'I am three',            es:'Tengo tres años',       e:'0033-20e3', p:true},
        {en:'I am four',             es:'Tengo cuatro años',     e:'0034-20e3', p:true},
        {en:'I like cats',           es:'Me gustan los gatos',   e:'1f431', p:true},
        {en:'I like dogs',           es:'Me gustan los perros',  e:'1f436', p:true},
        {en:'I am happy',            es:'Estoy feliz',           e:'1f601', p:true},
        {en:'I am sad',              es:'Estoy triste',          e:'1f622', p:true},
        {en:'I am hungry',           es:'Tengo hambre',          e:'1f974', p:true},
        {en:'I am tired',            es:'Estoy cansado',         e:'1f971', p:true},
        {en:'I am sleepy',           es:'Tengo sueño',           e:'1f634', p:true},
        {en:'I want milk',           es:'Quiero leche',          e:'1f95b', p:true},
        {en:'I want a biscuit',      es:'Quiero una galleta',    e:'1f36a', p:true},
        {en:'I love you',            es:'Te quiero',             e:'2764', p:true},
        {en:'Look at me!',           es:'¡Mírame!',              e:'1f440', p:true},
        {en:'That is a cat',         es:'Eso es un gato',        e:'1f431', p:true},
        {en:'That is a dog',         es:'Eso es un perro',       e:'1f436', p:true},
        {en:'The cat is big',        es:'El gato es grande',     e:'1f431', p:true},
        {en:'The dog is small',      es:'El perro es pequeño',   e:'1f436', p:true},
        {en:'One two three, go!',    es:'Uno dos tres, ¡ya!',    e:'1f3c3', p:true},
        {en:'Touch your nose',       es:'Toca tu nariz',         e:'1f443', p:true},
        {en:'Touch your head',       es:'Toca tu cabeza',        e:'1f9e0', p:true},
        {en:'Clap your hands',       es:'Da palmitas',           e:'1f44f', p:true},
        {en:'Jump up!',              es:'¡Salta!',               e:'1f939', p:true},
        {en:'Sit down',              es:'Siéntate',              e:'1fa91', p:true},
        {en:'Stand up',              es:'Levántate',             e:'1f9cd', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // BÁSICO  4–6 años
  // ══════════════════════════════════════════════════════════════
  basic: [
    { id: 'food_b', label: 'Comida', icon: '🍕', color: '#f97316',
      items: [
        {en:'Bread',    es:'Pan',        e:'1f35e'}, {en:'Milk',      es:'Leche',     e:'1f95b'},
        {en:'Egg',      es:'Huevo',      e:'1f95a'}, {en:'Pizza',     es:'Pizza',     e:'1f355'},
        {en:'Cookie',   es:'Galleta',    e:'1f36a'}, {en:'Cake',      es:'Tarta',     e:'1f370'},
        {en:'Ice cream',es:'Helado',     e:'1f368'}, {en:'Soup',      es:'Sopa',      e:'1f35c'},
        {en:'Cheese',   es:'Queso',      e:'1f9c0'}, {en:'Sandwich',  es:'Bocadillo', e:'1f96a'},
        {en:'Rice',     es:'Arroz',      e:'1f35a'}, {en:'Pasta',     es:'Pasta',     e:'1f35d'},
        {en:'Salad',    es:'Ensalada',   e:'1f957'}, {en:'Juice',     es:'Zumo',      e:'1f9c3'},
        {en:'Water',    es:'Agua',       e:'1f4a7'}, {en:'Chocolate', es:'Chocolate', e:'1f36b'},
        {en:'Butter',   es:'Mantequilla',e:'1f9c8'}, {en:'Yogurt',   es:'Yogur',     e:'1f964'},
        {en:'Pancake',  es:'Tortita',    e:'1f95e'}, {en:'Carrot',   es:'Zanahoria', e:'1f955'},
      ]},
    { id: 'clothes_b', label: 'Ropa', icon: '👕', color: '#ec4899',
      items: [
        {en:'Shirt',    es:'Camiseta',   e:'1f455'}, {en:'Pants',    es:'Pantalón',  e:'1f456'},
        {en:'Shoes',    es:'Zapatos',    e:'1f45f'}, {en:'Socks',    es:'Calcetines',e:'1f9e6'},
        {en:'Hat',      es:'Sombrero',   e:'1f9e2'}, {en:'Dress',    es:'Vestido',   e:'1f457'},
        {en:'Jacket',   es:'Chaqueta',   e:'1f9e5'}, {en:'Scarf',    es:'Bufanda',   e:'1f9e3'},
        {en:'Gloves',   es:'Guantes',    e:'1f9e4'}, {en:'Boots',    es:'Botas',     e:'1f97e'},
        {en:'Coat',     es:'Abrigo',     e:'1f9e5'}, {en:'Skirt',    es:'Falda',     e:'1f457'},
        {en:'Pyjamas',  es:'Pijama',     e:'1f634'}, {en:'Trainers', es:'Deportivas',e:'1f45f'},
        {en:'Jumper',   es:'Jersey',     e:'1f9e5'}, {en:'T-shirt',  es:'Camiseta',  e:'1f455'},
      ]},
    { id: 'home_b', label: 'Casa', icon: '🏠', color: '#14b8a6',
      items: [
        {en:'House',    es:'Casa',       e:'1f3e0'}, {en:'Door',     es:'Puerta',    e:'1f6aa'},
        {en:'Bed',      es:'Cama',       e:'1f6cf'}, {en:'Chair',    es:'Silla',     e:'1fa91'},
        {en:'Table',    es:'Mesa',       e:'1f6cb'}, {en:'Book',     es:'Libro',     e:'1f4da'},
        {en:'Window',   es:'Ventana',    e:'1fa9f'}, {en:'Bath',     es:'Baño',      e:'1f6c1'},
        {en:'Kitchen',  es:'Cocina',     e:'1f373'}, {en:'Garden',   es:'Jardín',    e:'1f33f'},
        {en:'Lamp',     es:'Lámpara',    e:'1f4a1'}, {en:'TV',       es:'Televisión',e:'1f4fa'},
        {en:'Fridge',   es:'Nevera',     e:'1f9ca'}, {en:'Stairs',   es:'Escaleras', e:'1f3e0'},
        {en:'Sofa',     es:'Sofá',       e:'1f6cb'}, {en:'Bedroom',  es:'Dormitorio',e:'1f6cf'},
      ]},
    { id: 'family_b', label: 'Familia', icon: '👨‍👩‍👧', color: '#8b5cf6',
      items: [
        {en:'Mum',      es:'Mamá',       e:'1f469'}, {en:'Dad',      es:'Papá',      e:'1f468'},
        {en:'Baby',     es:'Bebé',       e:'1f476'}, {en:'Sister',   es:'Hermana',   e:'1f467'},
        {en:'Brother',  es:'Hermano',    e:'1f466'}, {en:'Grandma',  es:'Abuela',    e:'1f475'},
        {en:'Grandpa',  es:'Abuelo',     e:'1f474'}, {en:'Aunt',     es:'Tía',       e:'1f469'},
        {en:'Uncle',    es:'Tío',        e:'1f468'}, {en:'Friend',   es:'Amigo',     e:'1f91d'},
        {en:'Boy',      es:'Niño',       e:'1f466'}, {en:'Girl',     es:'Niña',      e:'1f467'},
        {en:'Baby brother',es:'Hermanito',e:'1f476'},{en:'Baby sister',es:'Hermanita',e:'1f476'},
      ]},
    { id: 'days_b', label: 'Días', icon: '📅', color: '#6bcb77',
      items: [
        {en:'Monday',   es:'Lunes',      e:'1f4c5'}, {en:'Tuesday',  es:'Martes',    e:'1f4c5'},
        {en:'Wednesday',es:'Miércoles',  e:'1f4c5'}, {en:'Thursday', es:'Jueves',    e:'1f4c5'},
        {en:'Friday',   es:'Viernes',    e:'1f4c5'}, {en:'Saturday', es:'Sábado',    e:'1f389'},
        {en:'Sunday',   es:'Domingo',    e:'26ea'},  {en:'Today',    es:'Hoy',       e:'1f4c6'},
        {en:'Tomorrow', es:'Mañana',     e:'1f305'}, {en:'Yesterday',es:'Ayer',      e:'1f303'},
        {en:'Weekend',  es:'Fin de semana',e:'1f389'},{en:'Holiday', es:'Vacaciones',e:'1f334'},
      ]},
    { id: 'toys_b', label: 'Juguetes', icon: '🧸', color: '#ff6b9d',
      items: [
        {en:'Ball',     es:'Pelota',     e:'26bd'},  {en:'Toy',      es:'Juguete',   e:'1f9f8'},
        {en:'Doll',     es:'Muñeca',     e:'1f9b8'}, {en:'Car',      es:'Coche',     e:'1f697'},
        {en:'Bike',     es:'Bici',       e:'1f6b2'}, {en:'Kite',     es:'Cometa',    e:'1fa81'},
        {en:'Robot',    es:'Robot',      e:'1f916'}, {en:'Puzzle',   es:'Puzzle',    e:'1f9e9'},
        {en:'Train',    es:'Tren',       e:'1f682'}, {en:'Balloon',  es:'Globo',     e:'1f388'},
        {en:'Teddy bear',es:'Osito',     e:'1f9f8'}, {en:'Blocks',  es:'Bloques',   e:'1f9f1'},
        {en:'Slide',    es:'Tobogán',    e:'1f6d9'}, {en:'Swing',   es:'Columpio',  e:'1f333'},
      ]},
    { id: 'phrases_basic', label: 'Mis frases', icon: '💬', color: '#f97316',
      items: [
        {en:'My name is Pepe',           es:'Me llamo Pepe',             e:'1f476', p:true},
        {en:'I am five years old',       es:'Tengo cinco años',          e:'0035-20e3', p:true},
        {en:'I am six years old',        es:'Tengo seis años',           e:'0036-20e3', p:true},
        {en:'I live in Spain',           es:'Vivo en España',            e:'1f1ea-1f1f8', p:true},
        {en:'I have a dog',              es:'Tengo un perro',            e:'1f436', p:true},
        {en:'I have a cat',              es:'Tengo un gato',             e:'1f431', p:true},
        {en:'I have a brother',          es:'Tengo un hermano',          e:'1f466', p:true},
        {en:'I have a sister',           es:'Tengo una hermana',         e:'1f467', p:true},
        {en:'My favourite colour is red',es:'Mi color favorito es el rojo',e:'2764', p:true},
        {en:'My favourite food is pizza',es:'Mi comida favorita es la pizza',e:'1f355', p:true},
        {en:'My mum is nice',            es:'Mi mamá es simpática',      e:'1f469', p:true},
        {en:'My dad is funny',           es:'Mi papá es gracioso',       e:'1f468', p:true},
        {en:'I like playing',            es:'Me gusta jugar',            e:'1f3ae', p:true},
        {en:'I like swimming',           es:'Me gusta nadar',            e:'1f3ca', p:true},
        {en:'I like drawing',            es:'Me gusta dibujar',          e:'1f58c', p:true},
        {en:'I do not like vegetables',  es:'No me gustan las verduras', e:'1f966', p:true},
        {en:'Can I have some water?',    es:'¿Me das agua?',             e:'1f4a7', p:true},
        {en:'Can I go to the toilet?',   es:'¿Puedo ir al baño?',       e:'1f6bd', p:true},
        {en:'I can jump',                es:'Puedo saltar',              e:'1f939', p:true},
        {en:'I can run fast',            es:'Puedo correr rápido',       e:'1f3c3', p:true},
        {en:'I cannot swim',             es:'No puedo nadar',            e:'1f6ab', p:true},
        {en:'It is sunny today',         es:'Hoy hace sol',              e:'2600', p:true},
        {en:'It is raining today',       es:'Hoy llueve',                e:'1f327', p:true},
        {en:'Today is Monday',           es:'Hoy es lunes',              e:'1f4c5', p:true},
        {en:'I am going to school',      es:'Voy al colegio',            e:'1f3eb', p:true},
        {en:'School is fun!',            es:'¡El colegio mola!',         e:'1f3eb', p:true},
        {en:'I am wearing a red shirt',  es:'Llevo una camiseta roja',   e:'1f455', p:true},
        {en:'This is my friend',         es:'Este es mi amigo',          e:'1f91d', p:true},
        {en:'Come and play with me!',    es:'¡Ven a jugar conmigo!',     e:'1f3ae', p:true},
        {en:'That is not mine',          es:'Eso no es mío',             e:'274c', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // INTERMEDIO  6–8 años
  // ══════════════════════════════════════════════════════════════
  intermediate: [
    { id: 'actions_i', label: 'Verbos', icon: '🏃', color: '#ff6b6b',
      items: [
        {en:'Run',    es:'Correr',   e:'1f3c3'}, {en:'Jump',   es:'Saltar',  e:'1f939'},
        {en:'Walk',   es:'Caminar',  e:'1f6b6'}, {en:'Swim',   es:'Nadar',   e:'1f3ca'},
        {en:'Dance',  es:'Bailar',   e:'1f483'}, {en:'Sing',   es:'Cantar',  e:'1f3a4'},
        {en:'Read',   es:'Leer',     e:'1f4da'}, {en:'Write',  es:'Escribir',e:'270d'},
        {en:'Draw',   es:'Dibujar',  e:'1f58c'}, {en:'Eat',    es:'Comer',   e:'1f372'},
        {en:'Drink',  es:'Beber',    e:'1f964'}, {en:'Sleep',  es:'Dormir',  e:'1f634'},
        {en:'Play',   es:'Jugar',    e:'1f3ae'}, {en:'Fly',    es:'Volar',   e:'1f6eb'},
        {en:'Climb',  es:'Trepar',   e:'1f9d7'}, {en:'Ride',   es:'Montar',  e:'1f6b4'},
        {en:'Cook',   es:'Cocinar',  e:'1f373'}, {en:'Paint',  es:'Pintar',  e:'1f58c'},
        {en:'Laugh',  es:'Reír',     e:'1f602'}, {en:'Cry',    es:'Llorar',  e:'1f622'},
        {en:'Shout',  es:'Gritar',   e:'1f4e3'}, {en:'Whisper',es:'Susurrar',e:'1f910'},
        {en:'Help',   es:'Ayudar',   e:'1f91d'}, {en:'Share',  es:'Compartir',e:'1f91c'},
      ]},
    { id: 'adjectives_i', label: 'Adjetivos', icon: '✨', color: '#fbbf24',
      items: [
        {en:'Big',    es:'Grande',   e:'1f4a5'}, {en:'Small',  es:'Pequeño', e:'1f424'},
        {en:'Fast',   es:'Rápido',   e:'1f4a8'}, {en:'Slow',   es:'Lento',   e:'1f422'},
        {en:'Happy',  es:'Feliz',    e:'1f601'}, {en:'Sad',    es:'Triste',  e:'1f622'},
        {en:'Funny',  es:'Gracioso', e:'1f602'}, {en:'Angry',  es:'Enfadado',e:'1f621'},
        {en:'Tired',  es:'Cansado',  e:'1f971'}, {en:'Hungry', es:'Hambriento',e:'1f974'},
        {en:'Hot',    es:'Caliente', e:'1f975'}, {en:'Cold',   es:'Frío',    e:'1f976'},
        {en:'Dirty',  es:'Sucio',    e:'1f9fc'}, {en:'Clean',  es:'Limpio',  e:'1f6bf'},
        {en:'Tall',   es:'Alto',     e:'1f9cd'}, {en:'Short',  es:'Bajo',    e:'1f9d2'},
        {en:'Old',    es:'Viejo',    e:'1f474'}, {en:'New',    es:'Nuevo',   e:'1f381'},
        {en:'Kind',   es:'Amable',   e:'1f970'}, {en:'Brave',  es:'Valiente',e:'1f9b8'},
        {en:'Clever', es:'Listo',    e:'1f9e0'}, {en:'Silly',  es:'Tonto',   e:'1f92a'},
        {en:'Loud',   es:'Ruidoso',  e:'1f4e3'}, {en:'Quiet',  es:'Tranquilo',e:'1f910'},
        {en:'Beautiful',es:'Bonito', e:'1f338'}, {en:'Ugly',   es:'Feo',     e:'1f631'},
      ]},
    { id: 'school_i', label: 'Colegio', icon: '🏫', color: '#6bcb77',
      items: [
        {en:'School',   es:'Colegio',   e:'1f3eb'}, {en:'Pencil',  es:'Lápiz',    e:'270f'},
        {en:'Pen',      es:'Bolígrafo', e:'1f58a'}, {en:'Book',    es:'Libro',    e:'1f4da'},
        {en:'Ruler',    es:'Regla',     e:'1f4cf'}, {en:'Scissors',es:'Tijeras',  e:'2702'},
        {en:'Bag',      es:'Mochila',   e:'1f392'}, {en:'Rubber',  es:'Goma',     e:'1f9f9'},
        {en:'Crayon',   es:'Cera',      e:'1f58d'}, {en:'Glue',    es:'Pegamento',e:'1f9f4'},
        {en:'Map',      es:'Mapa',      e:'1f5fa'}, {en:'Computer',es:'Ordenador',e:'1f4bb'},
        {en:'Teacher',  es:'Profesor',  e:'1f469-200d-1f3eb'},{en:'Classroom',es:'Clase',e:'1f4cb'},
        {en:'Homework', es:'Deberes',   e:'1f4da'}, {en:'Test',    es:'Examen',   e:'1f4dd'},
        {en:'Break time',es:'Recreo',   e:'26bd'},  {en:'Library', es:'Biblioteca',e:'1f4da'},
      ]},
    { id: 'transport_i', label: 'Transporte', icon: '🚗', color: '#0ea5e9',
      items: [
        {en:'Car',       es:'Coche',      e:'1f697'}, {en:'Bus',      es:'Autobús',  e:'1f68c'},
        {en:'Train',     es:'Tren',       e:'1f682'}, {en:'Plane',    es:'Avión',    e:'2708'},
        {en:'Boat',      es:'Barco',      e:'26f5'},  {en:'Bike',     es:'Bicicleta',e:'1f6b2'},
        {en:'Motorbike', es:'Moto',       e:'1f3cd'}, {en:'Helicopter',es:'Helicóptero',e:'1f681'},
        {en:'Rocket',    es:'Cohete',     e:'1f680'}, {en:'Taxi',     es:'Taxi',     e:'1f695'},
        {en:'Ambulance', es:'Ambulancia', e:'1f691'}, {en:'Fire truck',es:'Camión bomberos',e:'1f692'},
        {en:'Submarine', es:'Submarino',  e:'1f6a2'}, {en:'Tram',    es:'Tranvía',  e:'1f68a'},
      ]},
    { id: 'jobs_i', label: 'Profesiones', icon: '👨‍⚕️', color: '#8b5cf6',
      items: [
        {en:'Doctor',    es:'Médico',     e:'1f469-200d-2695-fe0f'}, {en:'Teacher',  es:'Profesor',e:'1f469-200d-1f3eb'},
        {en:'Firefighter',es:'Bombero',   e:'1f9d1-200d-1f692'},     {en:'Police',   es:'Policía', e:'1f46e'},
        {en:'Cook',      es:'Cocinero',   e:'1f9d1-200d-1f373'},     {en:'Farmer',   es:'Granjero',e:'1f9d1-200d-1f33e'},
        {en:'Pilot',     es:'Piloto',     e:'1f9d1-200d-2708-fe0f'}, {en:'Vet',      es:'Veterinario',e:'1f9d1-200d-2695-fe0f'},
        {en:'Singer',    es:'Cantante',   e:'1f3a4'},                 {en:'Painter',  es:'Pintor',  e:'1f9d1-200d-1f3a8'},
        {en:'Builder',   es:'Constructor',e:'1f477'},                 {en:'Driver',   es:'Conductor',e:'1f9d1-200d-1f692'},
        {en:'Nurse',     es:'Enfermero',  e:'1f469-200d-2695-fe0f'}, {en:'Dentist',  es:'Dentista',e:'1f9b7'},
      ]},
    { id: 'sports_i', label: 'Deportes', icon: '⚽', color: '#f97316',
      items: [
        {en:'Football',   es:'Fútbol',    e:'26bd'},  {en:'Basketball',es:'Baloncesto',e:'1f3c0'},
        {en:'Tennis',     es:'Tenis',     e:'1f3be'}, {en:'Swimming',  es:'Natación', e:'1f3ca'},
        {en:'Running',    es:'Correr',    e:'1f3c3'}, {en:'Cycling',   es:'Ciclismo', e:'1f6b4'},
        {en:'Gymnastics', es:'Gimnasia',  e:'1f938'}, {en:'Skiing',    es:'Esquí',    e:'26f7'},
        {en:'Dancing',    es:'Baile',     e:'1f483'}, {en:'Karate',    es:'Karate',   e:'1f94b'},
        {en:'Volleyball', es:'Voleibol',  e:'1f3d0'}, {en:'Baseball',  es:'Béisbol',  e:'26be'},
      ]},
    { id: 'phrases_inter', label: 'Frases I can', icon: '💪', color: '#ec4899',
      items: [
        {en:'I can swim',               es:'Puedo nadar',               e:'1f3ca', p:true},
        {en:'I can ride a bike',        es:'Puedo montar en bici',      e:'1f6b2', p:true},
        {en:'I can speak English',      es:'Puedo hablar inglés',       e:'1f1ec-1f1e7', p:true},
        {en:'I can count to ten',       es:'Puedo contar hasta diez',   e:'1f51f', p:true},
        {en:'I can play football',      es:'Puedo jugar al fútbol',     e:'26bd', p:true},
        {en:'I cannot fly',             es:'No puedo volar',            e:'1f6eb', p:true},
        {en:'I cannot drive a car',     es:'No puedo conducir un coche',e:'1f697', p:true},
        {en:'Can you help me please?',  es:'¿Puedes ayudarme por favor?',e:'1f91d', p:true},
        {en:'I like playing football',  es:'Me gusta jugar al fútbol',  e:'26bd', p:true},
        {en:'I love reading books',     es:'Me encanta leer libros',    e:'1f4da', p:true},
        {en:'I do not like homework',   es:'No me gustan los deberes',  e:'1f4da', p:true},
        {en:'My favourite sport is swimming',es:'Mi deporte favorito es nadar',e:'1f3ca', p:true},
        {en:'I play football on Saturday',  es:'Juego al fútbol los sábados', e:'26bd', p:true},
        {en:'My teacher is very nice',  es:'Mi profesora es muy simpática',e:'1f469-200d-1f3eb', p:true},
        {en:'I have got a new book',    es:'Tengo un libro nuevo',      e:'1f4da', p:true},
        {en:'She has got blue eyes',    es:'Ella tiene los ojos azules',e:'1f499', p:true},
        {en:'He has got brown hair',    es:'Él tiene el pelo marrón',   e:'1f9b1', p:true},
        {en:'We are best friends',      es:'Somos mejores amigos',      e:'1f91d', p:true},
        {en:'They are playing outside', es:'Están jugando fuera',       e:'1f3ae', p:true},
        {en:'It is very hot today',     es:'Hoy hace mucho calor',      e:'1f975', p:true},
        {en:'What is the weather like?',es:'¿Cómo está el tiempo?',     e:'2600', p:true},
        {en:'It is cold and windy',     es:'Hace frío y viento',        e:'1f32c', p:true},
        {en:'I am going to the park',   es:'Voy al parque',             e:'1f333', p:true},
        {en:'Let us play together!',    es:'¡Juguemos juntos!',         e:'1f91d', p:true},
        {en:'Well done! That is great!',es:'¡Muy bien! ¡Genial!',       e:'1f44f', p:true},
      ]},
    { id: 'dialogues_inter', label: 'Diálogos', icon: '🗣️', color: '#14b8a6',
      items: [
        {en:'Hello! How are you?',          es:'¡Hola! ¿Cómo estás?',          e:'1f44b', p:true},
        {en:'I am fine, thank you!',        es:'¡Estoy bien, gracias!',         e:'1f600', p:true},
        {en:'What is your name?',           es:'¿Cómo te llamas?',              e:'2753', p:true},
        {en:'My name is Carlos',            es:'Me llamo Carlos',               e:'1f466', p:true},
        {en:'How old are you?',             es:'¿Cuántos años tienes?',         e:'1f382', p:true},
        {en:'I am seven years old',         es:'Tengo siete años',              e:'0037-20e3', p:true},
        {en:'Where do you live?',           es:'¿Dónde vives?',                 e:'1f3e0', p:true},
        {en:'I live in Madrid',             es:'Vivo en Madrid',                e:'1f3e0', p:true},
        {en:'Do you have any brothers or sisters?',es:'¿Tienes hermanos?',      e:'1f46a', p:true},
        {en:'Yes, I have one brother',      es:'Sí, tengo un hermano',          e:'1f466', p:true},
        {en:'No, I am an only child',       es:'No, soy hijo único',            e:'1f9d1', p:true},
        {en:'What do you like doing?',      es:'¿Qué te gusta hacer?',          e:'1f914', p:true},
        {en:'I like playing video games',   es:'Me gusta jugar a videojuegos',  e:'1f3ae', p:true},
        {en:'Me too! That is great!',       es:'¡Yo también! ¡Genial!',         e:'1f44d', p:true},
        {en:'Can I play with you?',         es:'¿Puedo jugar contigo?',         e:'1f91d', p:true},
        {en:'Of course! Come on!',          es:'¡Claro! ¡Vamos!',               e:'1f3c3', p:true},
        {en:'Excuse me, where is the toilet?',es:'Perdona, ¿dónde está el baño?',e:'1f6bd', p:true},
        {en:'It is over there, on the left',es:'Está allí, a la izquierda',     e:'1f4cd', p:true},
        {en:'Thank you very much!',         es:'¡Muchas gracias!',              e:'1f60a', p:true},
        {en:'You are welcome!',             es:'¡De nada!',                     e:'1f44d', p:true},
        {en:'See you tomorrow!',            es:'¡Hasta mañana!',                e:'1f44b', p:true},
        {en:'Have a good day!',             es:'¡Que tengas un buen día!',      e:'2600', p:true},
        {en:'What time is lunch?',          es:'¿A qué hora es la comida?',     e:'1f37d', p:true},
        {en:'It is at one o\'clock',        es:'Es a la una',                   e:'1f550', p:true},
        {en:'I am hungry! What is for lunch?',es:'¡Tengo hambre! ¿Qué hay para comer?',e:'1f974', p:true},
      ]},
  ],

  // ══════════════════════════════════════════════════════════════
  // AVANZADO  8–10 años
  // ══════════════════════════════════════════════════════════════
  advanced: [
    { id: 'nature_a', label: 'Naturaleza', icon: '🌿', color: '#6bcb77',
      items: [
        {en:'Forest',    es:'Bosque',    e:'1f333'}, {en:'Mountain',  es:'Montaña',  e:'26f0'},
        {en:'River',     es:'Río',       e:'1f3de'}, {en:'Sea',       es:'Mar',      e:'1f30a'},
        {en:'Beach',     es:'Playa',     e:'1f3d6'}, {en:'Desert',    es:'Desierto', e:'1f3dc'},
        {en:'Jungle',    es:'Selva',     e:'1f332'}, {en:'Lake',      es:'Lago',     e:'1f3de'},
        {en:'Volcano',   es:'Volcán',    e:'1f30b'}, {en:'Waterfall', es:'Cascada',  e:'1f3de'},
        {en:'Flower',    es:'Flor',      e:'1f338'}, {en:'Tree',      es:'Árbol',    e:'1f333'},
        {en:'Grass',     es:'Hierba',    e:'1f33f'}, {en:'Rock',      es:'Roca',     e:'1faa8'},
        {en:'Island',    es:'Isla',      e:'1f334'}, {en:'Cave',      es:'Cueva',    e:'1f9b7'},
      ]},
    { id: 'wild_animals_a', label: 'Animales salvajes', icon: '🦁', color: '#f97316',
      items: [
        {en:'Tiger',    es:'Tigre',     e:'1f42f'}, {en:'Giraffe',  es:'Jirafa',   e:'1f992'},
        {en:'Zebra',    es:'Cebra',     e:'1f993'}, {en:'Gorilla',  es:'Gorila',   e:'1f98d'},
        {en:'Crocodile',es:'Cocodrilo', e:'1f40a'}, {en:'Penguin',  es:'Pingüino', e:'1f427'},
        {en:'Dolphin',  es:'Delfín',    e:'1f42c'}, {en:'Shark',    es:'Tiburón',  e:'1f988'},
        {en:'Parrot',   es:'Loro',      e:'1f99c'}, {en:'Flamingo', es:'Flamenco', e:'1f9a9'},
        {en:'Panda',    es:'Panda',     e:'1f43c'}, {en:'Kangaroo', es:'Canguro',  e:'1f998'},
        {en:'Owl',      es:'Búho',      e:'1f989'}, {en:'Fox',      es:'Zorro',    e:'1f98a'},
        {en:'Wolf',     es:'Lobo',      e:'1f43a'}, {en:'Snake',    es:'Serpiente',e:'1f40d'},
      ]},
    { id: 'seasons_a', label: 'Estaciones y meses', icon: '🍂', color: '#fbbf24',
      items: [
        {en:'Spring',    es:'Primavera', e:'1f338'}, {en:'Summer',   es:'Verano',   e:'2600'},
        {en:'Autumn',    es:'Otoño',     e:'1f342'}, {en:'Winter',   es:'Invierno', e:'2744'},
        {en:'January',   es:'Enero',     e:'1f321'}, {en:'February', es:'Febrero',  e:'2764'},
        {en:'March',     es:'Marzo',     e:'1f340'}, {en:'April',    es:'Abril',    e:'1f327'},
        {en:'May',       es:'Mayo',      e:'1f33b'}, {en:'June',     es:'Junio',    e:'2600'},
        {en:'July',      es:'Julio',     e:'1f3d6'}, {en:'August',   es:'Agosto',   e:'1f4a5'},
        {en:'September', es:'Septiembre',e:'1f342'}, {en:'October',  es:'Octubre',  e:'1f383'},
        {en:'November',  es:'Noviembre', e:'1f343'}, {en:'December', es:'Diciembre',e:'2744'},
      ]},
    { id: 'daily_routine_a', label: 'Rutinas', icon: '⏰', color: '#4d96ff',
      items: [
        {en:'Wake up',        es:'Despertarse',    e:'1f4a4', p:true},
        {en:'Get dressed',    es:'Vestirse',       e:'1f455', p:true},
        {en:'Brush my teeth', es:'Lavarme los dientes',e:'1fa77', p:true},
        {en:'Have breakfast', es:'Desayunar',      e:'1f373', p:true},
        {en:'Go to school',   es:'Ir al colegio',  e:'1f3eb', p:true},
        {en:'Have lunch',     es:'Almorzar',       e:'1f37d', p:true},
        {en:'Do my homework', es:'Hacer los deberes',e:'1f4da', p:true},
        {en:'Have dinner',    es:'Cenar',          e:'1f372', p:true},
        {en:'Have a shower',  es:'Ducharme',       e:'1f6bf', p:true},
        {en:'Go to bed',      es:'Ir a dormir',    e:'1f6cf', p:true},
        {en:'I usually wake up at seven',es:'Normalmente me despierto a las siete',e:'1f550', p:true},
        {en:'I have breakfast at half past seven',es:'Desayuno a las siete y media',e:'1f373', p:true},
      ]},
    { id: 'conv_greetings_a', label: 'Conversaciones: Saludos', icon: '🤝', color: '#ff6b9d',
      items: [
        {en:'Hi! How are you doing?',          es:'¡Hola! ¿Cómo te va?',               e:'1f44b', p:true},
        {en:'I am doing great, thanks!',       es:'¡Muy bien, gracias!',                e:'1f600', p:true},
        {en:'Not bad, a bit tired though',     es:'Bien, aunque un poco cansado',       e:'1f971', p:true},
        {en:'Nice to meet you!',               es:'¡Encantado de conocerte!',           e:'1f91d', p:true},
        {en:'The pleasure is mine!',           es:'¡El placer es mío!',                 e:'1f60a', p:true},
        {en:'It is good to see you again!',    es:'¡Me alegra verte de nuevo!',         e:'1f604', p:true},
        {en:'I have not seen you for ages!',   es:'¡Hace siglos que no te veo!',        e:'1f635', p:true},
        {en:'How was your weekend?',           es:'¿Qué tal el fin de semana?',         e:'1f389', p:true},
        {en:'It was fantastic! We went to the beach.',es:'¡Fue fantástico! Fuimos a la playa.',e:'1f3d6', p:true},
        {en:'That sounds amazing!',            es:'¡Eso suena genial!',                 e:'1f929', p:true},
        {en:'See you later!',                  es:'¡Hasta luego!',                      e:'1f44b', p:true},
        {en:'Take care!',                      es:'¡Cuídate!',                          e:'1f496', p:true},
        {en:'Have a great time!',              es:'¡Que lo pases bien!',                e:'1f389', p:true},
        {en:'Good luck with your test!',       es:'¡Buena suerte en el examen!',        e:'1f340', p:true},
        {en:'Fingers crossed!',                es:'¡Crucemos los dedos!',               e:'1f91e', p:true},
      ]},
    { id: 'conv_school_a', label: 'Conversaciones: Colegio', icon: '🏫', color: '#6bcb77',
      items: [
        {en:'What subjects do you like?',      es:'¿Qué asignaturas te gustan?',        e:'1f4da', p:true},
        {en:'I love Maths and Science',        es:'Me encantan Mates y Ciencias',       e:'1f9ea', p:true},
        {en:'I find English a bit difficult',  es:'El inglés se me hace un poco difícil',e:'1f1ec-1f1e7', p:true},
        {en:'Do not worry, practice makes perfect!',es:'¡No te preocupes, la práctica hace al maestro!',e:'1f4aa', p:true},
        {en:'Can you repeat that please?',     es:'¿Puedes repetirlo por favor?',       e:'1f501', p:true},
        {en:'I do not understand',             es:'No entiendo',                        e:'1f615', p:true},
        {en:'Could you speak more slowly?',    es:'¿Podrías hablar más despacio?',      e:'1f422', p:true},
        {en:'How do you spell that?',          es:'¿Cómo se escribe?',                  e:'270f', p:true},
        {en:'What does this word mean?',       es:'¿Qué significa esta palabra?',       e:'2753', p:true},
        {en:'I got ten out of ten!',           es:'¡Saqué un diez!',                    e:'1f4af', p:true},
        {en:'I passed my English test!',       es:'¡Aprobé el examen de inglés!',       e:'1f389', p:true},
        {en:'We have got a school trip tomorrow',es:'Mañana tenemos una excursión',     e:'1f68c', p:true},
        {en:'I am really excited!',            es:'¡Estoy muy emocionado!',             e:'1f929', p:true},
        {en:'Our teacher is so funny!',        es:'¡Nuestra profe es muy graciosa!',    e:'1f602', p:true},
        {en:'I finished my homework early',    es:'Terminé los deberes pronto',         e:'1f44d', p:true},
      ]},
    { id: 'conv_family_a', label: 'Conversaciones: Familia', icon: '👨‍👩‍👧', color: '#8b5cf6',
      items: [
        {en:'Tell me about your family',       es:'Háblame de tu familia',              e:'1f46a', p:true},
        {en:'I have got a big family',         es:'Tengo una familia grande',           e:'1f46a', p:true},
        {en:'There are five of us at home',    es:'En casa somos cinco',                e:'1f3e0', p:true},
        {en:'My mum works as a doctor',        es:'Mi mamá trabaja de médico',          e:'1f469-200d-2695-fe0f', p:true},
        {en:'My dad is a teacher',             es:'Mi papá es profesor',                e:'1f468-200d-1f3eb', p:true},
        {en:'My grandparents live nearby',     es:'Mis abuelos viven cerca',            e:'1f475', p:true},
        {en:'We visit them every Sunday',      es:'Los visitamos cada domingo',         e:'26ea', p:true},
        {en:'My brother is older than me',     es:'Mi hermano es mayor que yo',         e:'1f466', p:true},
        {en:'My sister is two years younger',  es:'Mi hermana es dos años menor',       e:'1f467', p:true},
        {en:'We sometimes argue but we love each other',es:'A veces discutimos pero nos queremos mucho',e:'2764', p:true},
        {en:'My mum makes the best food!',     es:'¡Mi mamá hace la mejor comida!',     e:'1f373', p:true},
        {en:'We go on holiday together in summer',es:'En verano nos vamos de vacaciones juntos',e:'2600', p:true},
        {en:'Last year we went to the beach',  es:'El año pasado fuimos a la playa',    e:'1f3d6', p:true},
        {en:'It was the best holiday ever!',   es:'¡Fueron las mejores vacaciones!',    e:'1f929', p:true},
        {en:'I am lucky to have my family',    es:'Soy afortunado de tener mi familia', e:'2764', p:true},
      ]},
    { id: 'conv_hobbies_a', label: 'Conversaciones: Aficiones', icon: '🎸', color: '#ef4444',
      items: [
        {en:'What are your hobbies?',          es:'¿Cuáles son tus aficiones?',         e:'1f3ae', p:true},
        {en:'I really enjoy playing the guitar',es:'Me encanta tocar la guitarra',      e:'1f3b8', p:true},
        {en:'I have been playing for two years',es:'Llevo tocando dos años',            e:'1f3b5', p:true},
        {en:'I am also into drawing',          es:'También me gusta dibujar',           e:'1f58c', p:true},
        {en:'I draw comics in my free time',   es:'Dibujo cómics en mi tiempo libre',   e:'1f4d6', p:true},
        {en:'That is so cool!',                es:'¡Eso mola mucho!',                   e:'1f60e', p:true},
        {en:'Do you play any sports?',         es:'¿Practicas algún deporte?',          e:'26bd', p:true},
        {en:'I play football twice a week',    es:'Juego al fútbol dos veces a la semana',e:'26bd', p:true},
        {en:'My favourite team is Real Madrid',es:'Mi equipo favorito es el Real Madrid',e:'26bd', p:true},
        {en:'Who is your favourite player?',   es:'¿Quién es tu jugador favorito?',     e:'1f3c6', p:true},
        {en:'I also like watching films',      es:'También me gusta ver películas',     e:'1f3ac', p:true},
        {en:'What kind of films do you prefer?',es:'¿Qué tipo de películas prefieres?', e:'1f37f', p:true},
        {en:'I prefer adventure and comedy films',es:'Prefiero películas de aventuras y comedia',e:'1f3ac', p:true},
        {en:'Have you seen the new Marvel film?',es:'¿Has visto la nueva película de Marvel?',e:'1f9b8', p:true},
        {en:'Yes! It was absolutely brilliant!',es:'¡Sí! ¡Fue absolutamente brillante!',e:'1f929', p:true},
      ]},
    { id: 'conv_town_a', label: 'Conversaciones: Ciudad', icon: '🏙️', color: '#0ea5e9',
      items: [
        {en:'Excuse me, can you help me?',     es:'Perdona, ¿puedes ayudarme?',         e:'1f91d', p:true},
        {en:'Of course! What do you need?',    es:'¡Claro! ¿Qué necesitas?',            e:'1f604', p:true},
        {en:'How do I get to the park?',       es:'¿Cómo llego al parque?',             e:'1f333', p:true},
        {en:'Go straight on and turn left',    es:'Sigue recto y gira a la izquierda',  e:'1f4cd', p:true},
        {en:'Is it far from here?',            es:'¿Está lejos de aquí?',               e:'1f4cd', p:true},
        {en:'No, it is about five minutes away',es:'No, está a unos cinco minutos',     e:'1f552', p:true},
        {en:'Thank you so much!',              es:'¡Muchas gracias!',                   e:'1f60a', p:true},
        {en:'No problem, enjoy your day!',     es:'¡Sin problema, que disfrutes el día!',e:'2600', p:true},
        {en:'Where is the nearest supermarket?',es:'¿Dónde está el supermercado más cercano?',e:'1f6d2', p:true},
        {en:'There is one just around the corner',es:'Hay uno justo a la vuelta de la esquina',e:'1f3ea', p:true},
        {en:'I would like to buy a sandwich please',es:'Quisiera comprar un bocadillo por favor',e:'1f96a', p:true},
        {en:'That will be two pounds fifty',   es:'Son dos libras y cincuenta peniques', e:'1f4b0', p:true},
        {en:'Here you are. Keep the change!',  es:'Aquí tiene. ¡Quédese el cambio!',    e:'1f4b5', p:true},
        {en:'The park is beautiful in spring', es:'El parque es precioso en primavera', e:'1f338', p:true},
        {en:'I love this city!',               es:'¡Me encanta esta ciudad!',           e:'1f3d9', p:true},
      ]},
    { id: 'sentences_a', label: 'Frases completas', icon: '🗣️', color: '#c77dff',
      items: [
        {en:'I go to school every day',            es:'Voy al colegio cada día',            e:'1f3eb', p:true},
        {en:'My favourite colour is blue',         es:'Mi color favorito es el azul',       e:'1f499', p:true},
        {en:'I have two sisters and one brother',  es:'Tengo dos hermanas y un hermano',    e:'1f46a', p:true},
        {en:'I live in a big house near the park', es:'Vivo en una casa grande cerca del parque',e:'1f3e0', p:true},
        {en:'I can speak English and Spanish',     es:'Puedo hablar inglés y español',      e:'1f1ec-1f1e7', p:true},
        {en:'I like playing football on Sundays',  es:'Me gusta jugar al fútbol los domingos',e:'26bd', p:true},
        {en:'She is my best friend in the world',  es:'Ella es mi mejor amiga del mundo',   e:'1f91d', p:true},
        {en:'It is a beautiful sunny day today',   es:'Hoy es un día bonito y soleado',     e:'2600', p:true},
        {en:'The cat is sleeping on the sofa',     es:'El gato está durmiendo en el sofá',  e:'1f431', p:true},
        {en:'We are going on holiday next week',   es:'Nos vamos de vacaciones la semana que viene',e:'1f334', p:true},
        {en:'I would like to be a doctor when I grow up',es:'Quiero ser médico cuando sea mayor',e:'1f469-200d-2695-fe0f', p:true},
        {en:'Last summer we visited London',       es:'El verano pasado visitamos Londres', e:'1f1ec-1f1e7', p:true},
        {en:'In London it rained every day!',      es:'¡En Londres llovió todos los días!', e:'1f327', p:true},
        {en:'I think animals should be free',      es:'Creo que los animales deben ser libres',e:'1f98b', p:true},
        {en:'It is important to look after our planet',es:'Es importante cuidar nuestro planeta',e:'1f30d', p:true},
        {en:'Reading books makes you smarter',     es:'Leer libros te hace más listo',      e:'1f4da', p:true},
        {en:'I am going to study hard this year',  es:'Este año voy a estudiar mucho',      e:'1f4da', p:true},
        {en:'My dream is to travel around the world',es:'Mi sueño es viajar por el mundo',  e:'1f30d', p:true},
        {en:'English is useful for travelling',    es:'El inglés es útil para viajar',      e:'2708', p:true},
        {en:'Practice every day and you will improve',es:'Practica cada día y mejorarás',   e:'1f4aa', p:true},
      ]},
  ],
};

const BADGES = [
  { id: 'first_word',    icon: '🌟', label: 'Primera Palabra',    desc: 'Di tu primera palabra en inglés',   threshold: 1,   type: 'words' },
  { id: 'five_words',    icon: '🔥', label: '5 Palabras',         desc: 'Pronunciaste 5 palabras correctas', threshold: 5,   type: 'words' },
  { id: 'ten_words',     icon: '💪', label: '10 Palabras',        desc: '¡10 palabras dominadas!',           threshold: 10,  type: 'words' },
  { id: 'twenty_five',   icon: '🏆', label: 'Campeón',            desc: '25 palabras correctas en total',    threshold: 25,  type: 'words' },
  { id: 'fifty',         icon: '👑', label: 'Rey del Inglés',     desc: '50 palabras pronunciadas',          threshold: 50,  type: 'words' },
  { id: 'hundred',       icon: '💯', label: '¡100 Palabras!',     desc: '¡100 palabras correctas!',          threshold: 100, type: 'words' },
  { id: 'first_quiz',    icon: '🎯', label: 'Primer Quiz',        desc: 'Completaste tu primer quiz',        threshold: 1,   type: 'quizzes' },
  { id: 'quiz_master',   icon: '🧠', label: 'Quiz Master',        desc: '5 quizzes completados',             threshold: 5,   type: 'quizzes' },
  { id: 'perfect_quiz',  icon: '💎', label: 'Quiz Perfecto',      desc: '10/10 en un quiz',                  threshold: 1,   type: 'perfectQuizzes' },
  { id: 'first_write',   icon: '✏️', label: 'Primer Trazo',       desc: 'Escribiste tu primera palabra',     threshold: 1,   type: 'wordsWritten' },
  { id: 'write_ten',     icon: '📝', label: 'Escritor',           desc: '10 palabras escritas correctamente',threshold: 10,  type: 'wordsWritten' },
  { id: 'write_fifty',   icon: '📖', label: 'Gran Escritor',      desc: '50 palabras escritas',              threshold: 50,  type: 'wordsWritten' },
  { id: 'duo_win',       icon: '🆚', label: '¡Ganador Dúo!',      desc: 'Ganaste una partida multijugador',  threshold: 1,   type: 'duoWins' },
  { id: 'duo_five',      icon: '🎮', label: 'Jugador Dúo x5',     desc: '5 partidas dúo ganadas',            threshold: 5,   type: 'duoWins' },
  { id: 'streak_3',      icon: '⚡', label: 'Racha x3',           desc: '3 días seguidos practicando',       threshold: 3,   type: 'streak' },
  { id: 'streak_7',      icon: '🌈', label: 'Semana Completa',    desc: '7 días seguidos practicando',       threshold: 7,   type: 'streak' },
];

const AVATARS = ['🦁','🐯','🦊','🐸','🐼','🦄','🐲','🐺','🦋','🐬','🦅','🐧','🦒','🐘','🦈','🐙'];

function checkBadges(state) {
  const badges = [...(state.unlockedBadges || [])];
  for (const b of BADGES) {
    if (badges.includes(b.id)) continue;
    let val = 0;
    if      (b.type === 'words')          val = state.wordsCorrect     || 0;
    else if (b.type === 'quizzes')        val = state.quizzesCompleted || 0;
    else if (b.type === 'perfectQuizzes') val = state.perfectQuizzes   || 0;
    else if (b.type === 'wordsWritten')   val = state.wordsWritten     || 0;
    else if (b.type === 'duoWins')        val = state.duoWins          || 0;
    else if (b.type === 'streak')         val = state.streak           || 0;
    if (val >= b.threshold) badges.push(b.id);
  }
  return badges;
}

function loadState() {
  try {
    const s = localStorage.getItem('englishkids_v3');
    if (s) return JSON.parse(s);
  } catch(e) {}
  return {
    avatar: '🦁', name: '', xp: 0,
    wordsCorrect: 0, quizzesCompleted: 0, perfectQuizzes: 0,
    wordsWritten: 0, duoWins: 0, streak: 0, lastDate: null,
    unlockedBadges: [], learnedWords: {},
  };
}

function saveState(state) {
  try { localStorage.setItem('englishkids_v3', JSON.stringify(state)); } catch(e) {}
}

function getPlayerLevel(xp) {
  const lvls = [
    { lvl:1, min:0,    label:'Principiante', color:'#6bcb77' },
    { lvl:2, min:100,  label:'Aprendiz',     color:'#4d96ff' },
    { lvl:3, min:300,  label:'Explorador',   color:'#c77dff' },
    { lvl:4, min:600,  label:'Aventurero',   color:'#ffd93d' },
    { lvl:5, min:1000, label:'Campeón',      color:'#ff6b9d' },
    { lvl:6, min:1500, label:'Maestro',      color:'#ff6b6b' },
  ];
  let cur = lvls[0];
  for (const l of lvls) { if (xp >= l.min) cur = l; else break; }
  const next = lvls[lvls.indexOf(cur)+1];
  const pct  = next ? ((xp - cur.min)/(next.min - cur.min))*100 : 100;
  return { ...cur, next, pct };
}

Object.assign(window, { LEVELS, CATEGORIES, BADGES, AVATARS, checkBadges, loadState, saveState, getPlayerLevel });
